### ISSUE TITLE
Feedback for "Core Data and Services (CDS) Language Reference Documentation"

### ISSUE THREAD

**Issue by yogananda-muthaiah** [SAP-docs/btp-cloud-platform#1]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/855e00bd559742a3b8276fbed4af1008.html?version=Cloud

In help documentation, links are broken and that needs to be updated.

**Comment by renejeglinsky** [comment]
Thanks @yogananda-muthaiah ,

I'll look into this issue and get back to you when this is fixed.

all the best,
René

**Comment by renejeglinsky** [comment]
Hi @yogananda-muthaiah ,

I can't find a broken link on that page. The last one "Node.js API" has a redirect but still shows the content that is intended. I'll add the new link here, so that the redirect will not be needed anymore.

Is that the one you meant?

**Comment by yogananda-muthaiah** [comment]
@renejeglinsky 
Its all good now.. redirect url is taking to the right urls with content.

**Comment by renejeglinsky** [comment]
Thanks @yogananda-muthaiah ,

that's good news and thanks for getting in touch :)
