### ISSUE TITLE
Feedback for "Create a Destination"

### ISSUE THREAD

**Issue by NARAYANAGAYATHRI** [SAP-docs/btp-cloud-platform#105]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/3fa7934f5a714bf88d8490958211382f.html

Hi, Creating ABAP instance link is no more pointing to the right content

**Comment by nikolasimeonov77** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by DK1808** [comment]
Hi @NARAYANAGAYATHRI, thanks again for your feedback! This will be fixed with the next documentation update.
