### ISSUE TITLE
Feedback for "Using SAP SaaS Provisioning Service APIs to Manage Multitenant Applications"

### ISSUE THREAD

**Issue by Dr4kk0nnys** [SAP-docs/btp-cloud-platform#106]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/ed08c7dcb35d4082936c045e7d7b3ecd.html?locale=en-US&state=PRODUCTION&version=Cloud&q=saas%20manager

This documentation is completely deprecated, and is pretty much useless at this point, for how much guess work there is.

For starters, the credentials is such a crucial detail, that took our team hours to find. And it's simply glossed over on the table by the side of the POST request. It should be so much more visible.
There is missing information, such as the subscribing to a multitenant application missing the fact that there is a need to add a "planName" to the body of the request, otherwise it will return a 409 error.
And the requests are just plain wrong, there is no telling how to access the "/saas-manager/v1/application/subscriptions", it needs a separate token, that there is a documentation elsewhere ( to be found .... ) 

Correct me if I'm wrong, but this is not the right documentation for the https://api.sap.com/api/APISaasManagerService api

**Comment by DavidMitreski5** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by je-hal** [comment]
@danielforsap: This issue has been open for more than two weeks. Did you have a chance to check it? Do you need more information from the reporter?
Thanks!

**Comment by danielforsap** [comment]
Hi @je-hal,

We are updating the documentation, should be finished soon.

Once it's completed, I will respond.

Kind regards,
Daniel

**Comment by nikolasimeonov77** [comment]
Hi @danielforsap,
This issue has been opened for a month already. Could you please close it?

Thanks!

Nikola

**Comment by danielforsap** [comment]
Hi @nikolasimeonov77,

I don't want to close it since we are working on it.
Turns out, some important operational things about the login methods need to be changed as the consequence of this feedback (and not just documentation).

Will update soon.

Kind regards,
Daniel

**Comment by DavidMitreski5** [comment]
Hello @danielforsap, do we have an update for this issue?

**Comment by danielforsap** [comment]
Hi @DavidMitreski5,

The new authentication option has been added to SAP API Business Hub, and the updated version of the documentation will be released in a few days. I'll send the link to @Dr4kk0nnys by the end of this week.

Regards,
Daniel

**Comment by danielforsap** [comment]
Hi @Dr4kk0nnys,

We've added the Client Credentials authentication option to SAP API Business Hub - SaaS Provisioning Service APIs for app providers and updated the documentation according to your feedback.
Please see the updated version:
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/ed08c7dcb35d4082936c045e7d7b3ecd.html?version=Cloud

Note that some small changes will enter in the next doc release in two weeks, but the overall structure and content is fixed.

Kind regards,
Daniel

**Comment by MichaelGlaun** [comment]
Nice job!! 🏆
