### ISSUE TITLE
Feedback for "Core Principles"

### ISSUE THREAD

**Issue by phanikumarps** [SAP-docs/btp-cloud-platform#11]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/67dff4d26a444fe88d6471dee3532058.html

Exception class name mentioned in the help is incorrect: CX_XCO_RUNTIME_EXCETION
It should be CX_XCO_RUNTIME_EXCEPTION

**Comment by YasminavanRooij** [comment]
Hi Phanikumarps, 

Thank you for pointing this out. I've changed the exception class to CX_XCO_RUNTIME_EXCEPTION.

**Comment by YasminavanRooij** [comment]
You will be able to see the change on the SAP Help Portal after the next content update.
