### ISSUE TITLE
Feedback for "Trial Accounts and Free Tier"

### ISSUE THREAD

**Issue by mar-hol** [SAP-docs/btp-cloud-platform#116]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/046f127f2a614438b616ccfc575fdb16.html
" allow you to upgrade to paid service plans." depends on the selected service, eg when using Service plan "Free" for Kyma runtime "The upgrade to the paid plan is not yet supported." (see here https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/befe01d5d8864e59bf847fa5a5f3d669.html#free or https://discovery-center.cloud.sap/serviceCatalog/kyma-runtime?region=all&tab=service_plan) So maybe add something like "allow you to upgrade to paid service plans in case this is applicable for the respective service" and then also add a list with all exceptions (like Kyma) ... and ma<be also adapt the section here https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/524e1081d8dc4b0f9d055a6bec383ec3.html#update-to-a-paid-service-plan -> "Once you've reached the limits of the free plan, you can easily upgrade the free service plan to a paid plan. No data or configurations are lost."  so as this is not possible for Kyma runtime - what's the approach / needed steps to move from Free to Paid service plan?

**Comment by DavidMitreski5** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by AnjaNicoleKretz** [comment]
Hi @DavidMitreski5 working on it. I already updated the mentioned documentation (will be published in January), but am currently waiting on feedback to clarify some open questions.

**Comment by AnjaNicoleKretz** [comment]
Did receive feedback to open questions, everything looks fine.
