### ISSUE TITLE
Feedback for "Setting Up Your Own Application Router"

### ISSUE THREAD

**Issue by ymiquel** [SAP-docs/btp-cloud-platform#12]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/050d87a61faa4fb88f687abd7bdf16ce.html?locale=en-US

domain and host are deprecated in cloud foundry manifest.

**Comment by SarahErdmann** [comment]
Hi @ymiquel,
Thank you for your valuable feedback! 
I'll follow up on this. We'll update the page.

**Comment by SarahErdmann** [comment]
Hi @ymiquel,

Thanks again for the feedback. 
The lines about the host and domain in the sample code have been replaced by “routes”:
` routes:
- route: myHost-node-hello-world.xsapps.acme.ondemand.com`
You will be able to see the change on SAP Help Portal after the next content update.

Kind regards,
Sarah

**Comment by Peteva** [comment]
The update is now published at [https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/050d87a61faa4fb88f687abd7bdf16ce.html?locale=en-US](https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/050d87a61faa4fb88f687abd7bdf16ce.html?locale=en-USurl)
