### ISSUE TITLE
Feedback for "Deploy Content Using Generic Application Content Deployer"

### ISSUE THREAD

**Issue by piejanssens** [SAP-docs/btp-cloud-platform#122]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/07c679672e5f423e9dc631fc85b51da3.html

We should not be creating/composing mtar's directly...
Please update the document to have a solution based entirely on an mta.yaml file.

**Comment by piejanssens** [comment]
The result of the `mbt build` is a an mtar containing the mtad.yaml and MANIFEST.MF.
I belief that every reference to MANIFEST.MF can be removed from the public documentation
As developers we need to specify the deployment configuration in the mta.yaml definition.

**Comment by nikolasimeonov77** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by DavidMitreski5** [comment]
Hello @SarahErdmann , do we have an update for this issue? It has been open for quite a while now.

**Comment by SarahErdmann** [comment]
Hi @piejanssens,
Thank you for the valuable feedback! You're correct, we should not create mtar's directly. We are rewriting the page. 
The main steps in the procedure are now:
1.	Create a nested content.zip file that contains a zip file for each HTML5 application.
2.	Create an MTA development descriptor (mta.yaml file).
3.	In the MTA development descriptor (mta.yaml file), define the deployer module.
4.	To create an MTA archive (mtar file), build your content with the MTA Build Tool (MBT).
5.	Deploy the mtar.
The changes are to be published with the next content update of the SAP Help Portal.

**Comment by nikolasimeonov77** [comment]
You can find the documentation at https://help.sap.com/docs/btp/sap-business-technology-platform/deploy-content-using-generic-application-content-deployer?version=Cloud.

**Comment by piejanssens** [comment]
Thanks! It would be good to include a note or indicate the `path` property for the GACD module to allow specifying where the `content.zip` is fetched from.

**Comment by nikolasimeonov77** [comment]
Hello @SarahErdmann ,
Could you please check Pieter's suggestion above?

Thanks!

**Comment by SarahErdmann** [comment]
Hi @piejanssens,
Thanks for the suggestion! You're right. We are updating the code sample of the mta.yaml file in step 3. 
It should include a "path".
```
...
modules:
- name: ui_deployer
   type: com.sap.application.content
   path: deployer/ 
   requires:
    - name: uideployer_html5_repo_host
      parameters:
        content-target: true
...
```

The change is to be published with the next content update of the SAP Help Portal.
