### ISSUE TITLE
Feedback for "Content Deployment"

### ISSUE THREAD

**Issue by piejanssens** [SAP-docs/btp-cloud-platform#123]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/d3e23196166b443db17b3545c912dfc0.html

The workflow module sample is not showing how the actual workflow content is included in the `content-module`.

**Comment by DavidMitreski5** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by lilyanarangelova** [comment]
Thank you for your feedback. I'll forward it to my developers.

**Comment by piejanssens** [comment]
Hi @boyan-velinov, 

I'm not saying that the provided examples are wrong. The point is that these are too low level.
We are used to work with a higher level "project MTA development descriptor" `mta.yaml` and let `mbt build` deal with generating the `mtad.yaml`, `MANIFEST.MF` and package it in an `archive.mtar`. 

Since it has no added value for us as developers, there are no examples of `mtad.yaml` and `MANIFEST.MF` content in https://github.com/SAP-samples/cf-mta-examples. In the same way we shouldn't see this level in the SAP Help section on Content Deployment, instead we should see an example of an `mta.yaml`.

**Comment by boyan-velinov** [comment]
Hi @piejanssens 

I agree that this page of the documentation is not helpful for developers who use [SAP Business Application Studio](https://help.sap.com/docs/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/8f46c6e6f86641cc900871c903761fd4.html?locale=en-US) and/or [Cloud MTA Build Tool](https://sap.github.io/cloud-mta-build-tool/), namely starting with mta.yaml.

This[ part of the documentation](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/2a21055cc94b4a528a820f73e6fa7d69.html) is related to MTA deployment based on MTA deployment descriptor mtad.yaml, which might be inside of generated .mtar or outside.
It serves as a reference documentation what is possible with mtad.yaml and yes it is on a lower level. Note that this documentation cannot cover all kind of apps, services and contents provided by BTP Cloud Foundry. Each entitiy might have some peculiarity and needs certain MTA modelling. A proper place for documnetation about certain kind of app, service or content is inside its own documentation or inside in the  [SAP Business Application Studio](https://help.sap.com/docs/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/8f46c6e6f86641cc900871c903761fd4.html?locale=en-US) 

About Workflow, I would assume this is the proper page: https://help.sap.com/docs/WORKFLOW/e157c391253b4ecd93647bf232d18a83/b2df7c220b2245dcad11be747794c042.html?version=Cloud&locale=en-US

The improvements that we can do in[ Content Deployment](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/d3e23196166b443db17b3545c912dfc0.html) page are:

- Define how content deployment is done once it is passed by customer to MTA deployment service
- Refer documentation of  [SAP Business Application Studio](https://help.sap.com/docs/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/8f46c6e6f86641cc900871c903761fd4.html?locale=en-US) 
- Refer documentation of various known content services, like Workflow.

You are correct, the only one supported way to deploy MTA in CF from CMD is by using [MultiApps CF CLI plugin](https://github.com/cloudfoundry/multiapps-cli-plugin).

MultiApps CLI plugin provides possibility to deploy already generated MTA arhive (.mtar), which is result from MBT.
On the other side it provides possibility to deploy from directory that contains deployment descriptor (mtad.yaml) and already built app binaries.

Easy example can be seen into example repo:
https://github.com/SAP-samples/cf-mta-examples/tree/main/cf-app#deploy-from-directory

The command cf deploy is also documented in SAP Help Portal:
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/65ddb1b51a0642148c6b468a759a8a2e.html#deploy

Deploy from directory is useful when you maintain directly mtad.yaml (yes by hand) but you have the freedom to control the build of your apps - e.g. different builders, different sequence, etc.

[Defining Multitarget Application Development Descriptors](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/c2d31e70a86440a19e47ead0cb349fdb.html) might be improved and we will work on that by aiming to be more clear and explicit.

Best Regards,
Boyan

**Comment by lilyanarangelova** [comment]
I close this issue as Boyan already responded and the documentation is to be updated within next 2 weeks.
