### ISSUE TITLE
Feedback for "Security Events Logged by the CF Services"

### ISSUE THREAD

**Issue by rlaguswns** [SAP-docs/btp-cloud-platform#127]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/84acdc91c60c4f32b7c06cdbc442fdef.html

Hi, I found a broken link.

<br class="Apple-interchange-newline">SAP HANA Cloud, Adaptive Server Enterprise Instance	[Auditing](https://help.sap.com/viewer/46353c3b724f4934bb0671dd82044acd/2021_01_QRC/en-US/060dcc86632b44c8b89c466e15b86f27.html)

**Comment by DavidMitreski5** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by nikolasimeonov77** [comment]
@petiansap Could you please fix the link and respond to this issue when done?

**Comment by petiansap** [comment]
@nikolasimeonov77, fixing is in progress, but because the topic switched owners I'm still waiting for the reply of the current owner.

**Comment by petiansap** [comment]
I removed the link as the product has been discontinued for more than a year. 
@rlaguswns, thank you very much for your contribution!
