### ISSUE TITLE
Feedback for "Create an SAP SuccessFactors Extensibility Service Instance in the Cloud Foundry Environment"

### ISSUE THREAD

**Issue by mar-hol** [SAP-docs/btp-cloud-platform#131]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/8b774e4ca8be46a4830a021f727667ed.html?version=Cloud

the "New Instance or Subscription wizard" has changed as mandatory selection field "System Name" (between step d. and e.) has been introduced to select the SFSF system (registered and entitled). So no need to add json file in this step. You can manipulate the json file afterwards in the wizard
![image](https://user-images.githubusercontent.com/38477763/210523645-11f5de37-de79-4563-8452-beba51e47e1b.png)
![image](https://user-images.githubusercontent.com/38477763/210523730-07d22979-0f3e-4810-9cde-fc9f475c2353.png)
![image](https://user-images.githubusercontent.com/38477763/210523824-73d9e171-74ea-4c57-9545-0d1418e7e5f4.png)

This applies also to the  [Configure the Subaccount as a Trusted Service Provider in SAP SuccessFactors](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/9efe2a1d84c2458fb7b68d4df1bd13ee.html?version=Cloud) set up step (see screenshots)

**Comment by ekaterina-mitova** [comment]
Hi @mar-hol,
Thank you so much for letting me know! I will update the documentation, the changes will be available with the next release. 
Best regards,
Ekaterina
