### ISSUE TITLE
Feedback for "Developing Java in the Cloud Foundry Environment"

### ISSUE THREAD

**Issue by giselebrito** [SAP-docs/btp-cloud-platform#133]
https://help.sap.com/docs/btp/sap-business-technology-platform/developing-java-in-cloud-foundry-environment?q=java%20runtime

Any updates on Java 17 support?

**Comment by Joysie** [comment]
Hi @giselebrito,

Thank you for your question!
SAP Java Buildpack currently supports only Java 8 and 11. No near-future plans for supporting 17.

**FYI**: SapMachine supports Java 11, 17 and 19.

**Comment by Joysie** [comment]
I'm closing this issue now. 

If there are news on the topic, I'll reply here. Or you'll read about them in our official Release Notes :)

Best regards,
Gergana

**Comment by giselebrito** [comment]
https://people.sap.com/gisele.brito
