### ISSUE TITLE
Feedback for "Transporting Multitarget Applications in Cloud Foundry using CTS+"

### ISSUE THREAD

**Issue by I327556** [SAP-docs/btp-cloud-platform#134]
Hi Document Owner,

I'm contacting you regarding the help document:
https://help.sap.com/docs/btp/sap-business-technology-platform/transporting-multitarget-applications-in-cloud-foundry-using-cts

It has the following broken link:
[How to...Configure SAP BTP, Cloud Foundry environment for CTS](https://help.sap.com/doc/9aad207e90fa4da793d34114113e9254/Cloud/en-US/HowToCTS%2B_Guide_SCP_CF.pdf).

Could you please fix it and point to the relevant documentation?

Thank you and best regards,
Szabolcs

**Comment by nikolasimeonov77** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by lilyanarangelova** [comment]
Hi,
Thank you for your feedback. The link has been fixed.
Best regards,
Lilyana
