### ISSUE TITLE
Wrong link at "Profiling an Application Running on SAP JVM"

### ISSUE THREAD

**Issue by clnative** [SAP-docs/btp-cloud-platform#136]
https://help.sap.com/docs/btp/sap-business-technology-platform/profiling-application-running-on-sap-jvm

In the prerequisites it reads

> Open a debugging connection using an SSH tunnel. For more information, see [Debug an Application Running on SAP JVM](https://help.sap.com/docs/btp/sap-business-technology-platform/debug-application-running-on-sap-jvm)

The link goes to the page which is specific to SAP JVM. That is too specific: You could also be running a SapMachine-based container in this context. It would be better to link it to https://help.sap.com/docs/btp/sap-business-technology-platform/debugging-java-applications instead.

**Comment by clnative** [comment]
Perhaps also consider revising the title of the page and its content: How do I profile SapMachine-based containers?

For those who don't know: SapMachine is something like the successor of SAPJVM

**Comment by Joysie** [comment]
Hi @clnative ,

I'm sorry for this late reply! And thank you for your contribution and suggestion!

I'm not sure I should really change this link because the topic is "_Profiling an Application Running on **SAP JVM**_". The whole section is about SAP JVM, hence - the specific link is [Debug an Application Running on **SAP JVM**](https://help.sap.com/docs/btp/sap-business-technology-platform/debug-application-running-on-sap-jvm).

However, what we **can** do, is creating a new topic called "_Profiling an Application Running on **SapMachine**_" and  adding there a link to page [Debug an Application Running on **SapMachine**](https://help.sap.com/docs/btp/sap-business-technology-platform/debug-java-web-application-running-on-sapmachine).

**Comment by clnative** [comment]
> I'm not sure I should really change this link because the topic is "Profiling an Application Running on SAP JVM". The whole section is about SAP JVM, hence - the specific link is [Debug an Application Running on SAP JVM](https://help.sap.com/docs/btp/sap-business-technology-platform/debug-application-running-on-sap-jvm).

I agree.
All these topics are rather confusing for me, as most things which I was used to use in SAP JVM, there is a new counterpart in SAPMachine. I would need a translator for this (and hoped to find it in the documentation).

> However, what we can do, is creating a new topic called "Profiling an Application Running on SapMachine" and adding there a link to page [Debug a Java Web Application Running on SapMachine](https://help.sap.com/docs/btp/sap-business-technology-platform/debug-java-web-application-running-on-sapmachine).

Perhaps my previous statement and your one here brings us to the original issue that I have: How do I profile a SAPmachine-based CF application?
Is the page https://help.sap.com/docs/btp/sap-business-technology-platform/profiling-application-running-on-sap-jvm still valid also for SAPMachine-based containers?

**Comment by Joysie** [comment]
Hi Nico,

We're working on creating a proper docu page for profiling applications on SapMachine. The [current page](https://help.sap.com/docs/btp/sap-business-technology-platform/profiling-application-running-on-sap-jvm?version=Cloud) is not valid for this scenario - it's only for SAP JVM. 

I apologize for making you wait some more. And thank you a lot for your suggestion and contribution!

Best regards,
Gergana

**Comment by clnative** [comment]
No rush, please. 
Please take your time as needed.

**Comment by Joysie** [comment]
Hi Nico,

I'll close this issue for now. And when we're ready with the new doc, I'll add a new comment with the link here. 
I hope that's OK!

Best regards,
Gergana

**Comment by Joysie** [comment]
Hi Nico,

The new document is created and verified. See: [Profiling an Application Running on SapMachine](https://help.sap.com/docs/btp/sap-business-technology-platform/profiling-application-running-on-sapmachine?version=Cloud)

All the best,
Gergana
