### ISSUE TITLE
Feedback for "Audit Log Retrieval API for Global Accounts in the Cloud Foundry Environment"

### ISSUE THREAD

**Issue by mar-hol** [SAP-docs/btp-cloud-platform#137]
https://help.sap.com/docs/btp/sap-business-technology-platform/audit-log-retrieval-api-for-global-accounts-in-cloud-foundry-environment

Regarding bullet Point 1. "To entitle your global account with plan central for service Auditlog Management, choose Manage Accounts entry from the left-hand side menu in the control center." 

Control Center is SAP-internal stuff; customers are not able to access Control Center to manage entitlements.
Audit Log service is always free (include in BTP); see also [service description on SAP Discovery Center](https://discovery-center.cloud.sap/serviceCatalog/audit-log-service?service_plan=default&region=all&commercialModel=cloud)
Thus the part with Control Center is confusing in customer facing help doc. Please adjust accordingly.

BR, Marco

**Comment by mar-hol** [comment]
BTW: SAP Discovery Center only list "Default" service plan., but not the "central"-one the documentation refers to.
![image](https://user-images.githubusercontent.com/38477763/224154802-720bf71d-43ac-44c7-9e4a-4d29e34968fa.png)
https://discovery-center.cloud.sap/serviceCatalog/audit-log-service?service_plan=default&region=all&commercialModel=cpea&tab=service_plan

**Comment by mar-hol** [comment]
do we also have a list of events logged by Audit log on Global Account level (central service plan); like we have for events from the different cf services: https://help.sap.com/docs/btp/sap-business-technology-platform/security-events-logged-by-cf-services

**Comment by petiansap** [comment]
Hi Marco, thank you very much for your feedback! I'll work with the colleagues from the Audit Log team to correct the documanetation.

**Comment by petiansap** [comment]
Point 1 in the https://help.sap.com/docs/btp/sap-business-technology-platform/audit-log-retrieval-api-for-global-accounts-in-cloud-foundry-environment is removed. The colleagues from the dev team are discussing further the possibilities for having list of events logged by Audit log on Global Account level .
