### ISSUE TITLE
Feedback for "ABAP Compute Units"

### ISSUE THREAD

**Issue by BQUGKOCW** [SAP-docs/btp-cloud-platform#140]
https://help.sap.com/docs/btp/sap-business-technology-platform/abap-compute-units

Hello,

In the chapter about ABAP Compute Units you wrote:
"The system consists of at least 2 application servers of the size of 8 GB each.

When you order 4 ACUs or more, the system consists of at least 2 application servers of the size of 32 GB each."

Shouldn't it be 
"When you order 4 ACUs or more, the system consists of at least 2 application servers of the size of 32 GB each."

4 ACUs with 2 application servers each multiply to 8 application servers.

Kind regards
Michael

**Comment by sarahbaczyk** [comment]
Actually, I asked the colleague who originally gave me the text input for the ABAP Compute Units docu.
His statement is, that the so far implemented text still makes sense:
_"ich glaube der Kollege hat das each auf ACU bezogen und nicht auf die Applikationsserver. 
Ich möchte ja sagen, dass man 2*8 GB bekommt. 
Wenn man 4 ACUs oder mehr bestellt, bekommt man große Applikationsserver. 
Also so:
1 ACU = 16 GB = 2 * 8 GB
2 ACU = 32 GB = 4 * 8 GB
4 ACU = 64 GB = 2 * 32 GB
6 ACU = 96 GB = 3 * 32 GB
…
Also wenn mein Englisch richtig ist, dann kann der Satz so bleiben wie er ist. Das each bezieht sich auf den Applikationsserver."_
-> therefore, I will keep the text as it is.
