### ISSUE TITLE
[Bug] v3 specification about Extension Descriptors behavior differs from the content on the page "Defining MTA Extension Descriptors"

### ISSUE THREAD

**Issue by rolpat** [SAP-docs/btp-cloud-platform#141]
https://help.sap.com/docs/btp/sap-business-technology-platform/defining-mta-extension-descriptors

Dear authors,

I just got a bit confused when reading the section 2.2.1 of the v3 specification, where it is said about Extension Descriptors

"[...]
You can only add information via an extension, not change (=overwrite), or delete.
[...]",

but on the page linked above it is mentioned that

"[...]
You can do the following using an extension descriptor:
-	Add a new data in modules, resources, parameters, properties, provides, requires sections
-	Overwrite an existing data (in depth) in modules, resources, parameters, properties, provides, requires sections
[...]"

Actually, it (seems) to work like it is described on the link, that means that it is possible to add new parameters __and__ to overwrite existing ones.

Thanks for having a look at it!

Regards,
rolpat

**Comment by DavidMitreski5** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by lilyanarangelova** [comment]
Hi,
Thank you for your feedback. We'll update the documentation.

Best regards,
Lilyana

**Comment by rolpat** [comment]
Hi Lilyana,

Thanks a lot!

Best regards,
Roland

**Comment by lilyanarangelova** [comment]
Hi,
Section 2.2.1 of the v3 MTA Model specification was updated as follows:
<img width="929" alt="Screenshot 2023-04-07 at 10 08 33" src="https://user-images.githubusercontent.com/30077871/230560183-1d6e99dd-f27e-4d34-bae0-3570894d22f7.png">

It will be updated on sap.com next week.
Best regards,
Lilyana
