### ISSUE TITLE
Feedback for "HTTP Communication via Communication Arrangements"

### ISSUE THREAD

**Issue by horsemanjackyliu** [SAP-docs/btp-cloud-platform#143]
https://help.sap.com/docs/btp/sap-business-technology-platform/http-communication-via-communication-arrangements

the following sentence is not permitted in Eclipse at all

     out->write( lx_http_dest_provider_error->get_text( ) ).

**Comment by felixdraeger** [comment]
Thanks for your feedback! 
It is intended that the exception is handled within the ADT classrunner (if_adt_oo_classrun). The exception would then be output in the console. We decided to leave the definition of the class out of the code example to avoid too long examples. However, you are right that this can lead to confusion. 
You can of course use your own exception handling here. It is not mandatory to output the text in the console. 
 I will update the documentation accordingly.

Best
Felix
