### ISSUE TITLE
Feedback for "Define SAP S/4HANA Cloud Extensibility Service Descriptor JSON/YAML File"

### ISSUE THREAD

**Issue by horsemanjackyliu** [SAP-docs/btp-cloud-platform#148]
https://help.sap.com/docs/btp/sap-business-technology-platform/define-sap-s-4hana-cloud-extensibility-service-descriptor-json-yaml-file

The YAML file  topicRules does not support subscribeFilter . It is a bug  .

**Comment by ekaterina-mitova** [comment]
Hi @horsemanjackyliu,

You set the subscribeFilter property in the Event Mesh service descriptor and its value must be the same as the value of the namespace property from the SAP S/4HANA Cloud Extensibility service descriptor. See https://help.sap.com/docs/btp/sap-business-technology-platform/define-sap-event-mesh-service-descriptor-json-yaml-file

Best regards, 
Ekaterina
