### ISSUE TITLE
Feedback for "Federation Attribute Settings of Any Identity Provider"

### ISSUE THREAD

**Issue by I040926** [SAP-docs/btp-cloud-platform#149]
Hi Colleagues,

https://help.sap.com/docs/btp/sap-business-technology-platform/federation-attribute-settings-of-any-identity-provider?version=Cloud

As far as I can see the text "For more information, see the related link." does not contain a valid link.  Can you please check it?
Thanks,
Gábor

**Comment by annawenger20** [comment]
Hi @I040926 - as far as I understand this, it refers to the link at the bottom of the page in the section "Related Links". In this case [Map Role Collections to User Groups](https://help.sap.com/docs/btp/sap-business-technology-platform/map-role-collections-to-user-groups?version=Cloud). 
I hope this clarifies the issue, please re-open it if you'd like to discuss further.
Thanks a lot and have a good day,
Anna
