### ISSUE TITLE
Feedback for "Multitarget Applications in the Cloud Foundry Environment"

### ISSUE THREAD

**Issue by DanSchlachter** [SAP-docs/btp-cloud-platform#150]
https://help.sap.com/docs/btp/sap-business-technology-platform/multitarget-applications-in-cloud-foundry-environment

Why is it showing `SAP Web IDE` on the screenshots? Shouldn't this be BAS?

**Comment by lilyanarangelova** [comment]
Hi @DanSchlachter,
Thank you for your feedback! We'll update the documentation.

Best regards,
Lilyana

**Comment by lilyanarangelova** [comment]
Hi,
We've updated the documentation and added information about BAS. The changes will be visible for customers with the next BTP release.

<img width="1036" alt="Screenshot 2023-05-12 at 15 24 51" src="https://github.com/SAP-docs/btp-cloud-platform/assets/30077871/9ce309ba-964c-4144-bc6a-c4d635db8698">


Best regards,
Lilyana
