### ISSUE TITLE
Feedback for "Application Security Descriptor Configuration Syntax"

### ISSUE THREAD

**Issue by r00k13d3v** [SAP-docs/btp-cloud-platform#153]
Good morning experts!

I have been reviewing the xsuaa document and when creating a service without parameters (without adding the xs-security) the tenant-mode is shared by default. I don't know if it is a bug or if I have to modify the documentation.

Best regards! 

https://help.sap.com/docs/btp/sap-business-technology-platform/application-security-descriptor-configuration-syntax

**Comment by MichaelPShea** [comment]
@r00k13d3v: Good catch. The default tenant-mode is determined by the plan you used when you created the service instance. For the application plan and apiaccess plan, the default is shared. We were considering offering another plan with a default of dedicated. Looks like we forgot to adjust our documentation. I'll change the documentation. The change will be visible about the middle of June.
