### ISSUE TITLE
Feedback for "Enterprise Accounts"

### ISSUE THREAD

**Issue by rlaguswns** [SAP-docs/btp-cloud-platform#158]
In the page https://help.sap.com/docs/btp/sap-business-technology-platform/enterprise-accounts

https://www.sap.com/partners/partner-program/partneredge-build.html
This link is broken.

**Comment by nikolasimeonov77** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by annawenger20** [comment]
Thanks a lot for spotting this - the link will be updated to https://www.sap.com/partners/partner-program/build.html with the next release on SAP Help Portal. 
Kind regards, Anna
