### ISSUE TITLE
Feedback for "Configure Entitlements and Quotas for Subaccounts"

### ISSUE THREAD

**Issue by dsimov** [SAP-docs/btp-cloud-platform#16]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/5ba357b4fa1e4de4b9fcc4ae771609da.html?locale=en-US&version=Cloud

This page does not help with the message that I got:
Unable to start application example: Cannot start application 'example'; there is no compute unit quota for subaccount 'hzahylnfp5'.
You can:
1. Check the compute unit quotas of your subaccount
2. Configure compute unit size for the application with parameter --size

**Comment by AnjaNicoleKretz** [comment]
Hi Jimmy,

I had a look and so far I think the issue may lie in the error message, not the documentation, as the message mentions "compute unit quota" and not just "quota". 

Best,

Anja

**Comment by dsimov** [comment]
Yes, Anja. 
I'd suggest that you check why the message is pointing to this help topic. If there is another topic that is a better match to the message, you can provide that in the message. If there is no such topic, it might be worth writing one.
Regards
Jimmy

**Comment by nikolasimeonov77** [comment]
Hi @dsimov, 
This repository is only used to review feedback on documentation. Please use other more appropriate channels to report problems with the product, service, or tool being described (such as the [SAP Community Q&A](https://answers.sap.com/) and the [SAP Support Portal](https://support.sap.com/)). See also our [Dos and Don'ts](https://help.sap.com/products/open-documentation-initiative/contribution-guidelines/dos-and-donts.html).
