### ISSUE TITLE
Doubt about prerequisites for Kyma environment

### ISSUE THREAD

**Issue by r00k13d3v** [SAP-docs/btp-cloud-platform#169]
### Issue description

Hello experts! 

I'm reviewing the documentation and following the onboarding process for the Kyma environment. The documentation states that the only prerequisite is to have the Kyma environment associated, but when attempting to create it that way, an error occurs indicating that it also needs to have the entitlements of Service Manager. Is it necessary to include them in the documentation, or are they a "base" of entitlements that should already be present?

![image](https://github.com/SAP-docs/btp-cloud-platform/assets/106471374/3f82af81-bc19-4f83-9697-ba3e5eb64b67)

Thanks in advance! 

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

Getting Started in the Kyma Environment

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/getting-started-in-kyma-environment?locale=en-US

**Comment by NHingerl** [comment]
Hi [r00k13d3v](https://github.com/r00k13d3v), thank you for noticing this! We're checking with our devs and will provide a solution asap.

**Comment by grego952** [comment]
Hi @r00k13d3v 
Thanks for your feedback.
It looks like you're missing some entitlements in your account because the "base entitlements" should automatically be present.
It's probably an issue that should be reported to [Commercial Infrastructure Services (CIS)](https://wiki.one.int.sap/wiki/display/CPC15N/CIS+Core+and+Provisioning). [This guide](https://wiki.one.int.sap/wiki/display/CPC15N/How+to+request+help+from+the+CIS+operations+team) should help you with reporting this issue.
If there's anything else that I can help you with, please let me know.

**Comment by r00k13d3v** [comment]
Hi @grego952 

Thanks for the quick response. In our case, we always perform an entitlements cleanup in the subaccount and add the necessary ones for each service that is going to be enabled. Are these base entitlements documented somewhere in the documentation? It would be very helpful to have a reference to that document in the Kyma documentation.

Best regards and thank you!

**Comment by grego952** [comment]
Hi @r00k13d3v,
Thanks for your feedback.
The Getting Started in Kyma Environment doc is for users who create the Kyma Environment instance for the first time. In this case, the Service Management (SM) entitlement is added by default.
You're completely right. We should have a note with information about SM entitlement for users who would like to reuse the subaccount.
We'll keep you posted under this issue.

**Comment by IwonaLanger** [comment]
Hi @r00k13d3v, 
I've added [a note](https://help.sap.com/docs/btp/sap-business-technology-platform/getting-started-in-kyma-environment?locale=en-US&version=Cloud) about the required Service Manager entitlement in the Prerequisites sections.
Thanks again for your inquiry!
