### ISSUE TITLE
Feedback for "Valid Redirect URIs for OAuth 2.0 Authorization Code Flow"

### ISSUE THREAD

**Issue by Smux** [SAP-docs/btp-cloud-platform#17]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/4f28d335fa2543d7b24e27f7e8e399f7.html?locale=en-US

When the redirect URIs are not maintained, it obviously works after deployment of the MTA project. 
In the past as soon as we maintained at least one redirect-uri it seemed to exclude the host on which it was deployed and only specifically allowed the URIs that were maintained. I now tested again maintaining a redirect-uri (in my case localhost for local development) and still the deployed version is working fine. So it seems that this configuration is not excluding any URI that does not match but it seems to allow the host of the deployed app as well as additionally the configured redirect URIs 

Is this correct?

**Comment by MichaelPShea** [comment]
@Smux : I spoke to my development team. The problem you describe appears when you use local docker setups, for example. In general, only the redirects that are configured are allowed. There is an exception: We always allow *.cfapps.<landscape>. SAP BTP trusts itself. Does that help?

**Comment by Smux** [comment]
Hello @MichaelPShea but I actually do not use a local docker setup. 
It is a little confusing. It seems to allow localhost as well without any redirect URI maintained in the XSUAA config. 
So is this a "bug"? I just want to understand how the mechanism works because it seems to be unclear atm.

**Comment by MichaelPShea** [comment]
@Smux , Sorry but I am a little confused. So you are deploying the app to your subaccount then? Then you are maintaining the redirect URIs to https://myapp.localhost/mypath? Or are you redirecting to https://myapp.mysubdomain.cfapps.mylandscape/mypath?

**Comment by Smux** [comment]
Both :) I run my app locally with a local approuter for development purpose. There I am running on http://localhost:5001. When I deploy my app to the cloud it is exposed via the router on a path similar to the last one you described.
According to your initial message you allow .cfapps URLs which means that the deployed version always works without any maintained redirect URI in the xs security. However the localhost should not work, but it does in my case :o

**Comment by MichaelPShea** [comment]
Hi Smux,
Sorry for the delay in answering. I am going through your message with my development colleague. We are not quite clear from where to where are you redirecting? Can you give us the UAA login URL and the redirect URL that you are sending to the UAA?

**Comment by MichaelPShea** [comment]
Just to follow up, I found a blog post that might interest you: https://blogs.sap.com/2021/11/04/ui5-local-development-with-ability-to-access-backend-services-on-the-sap-btp-cf/

**Comment by MichaelPShea** [comment]
@Smux : Can you provide the requested information? Thanks!

**Comment by Smux** [comment]
Hello Michael,
I am using the @sap/approuter and just bind it to an existing XSUAA instance via default-env.json file. The XSUAA instance is inside my SAP BTP Cloud Foundry space on my BTP subaccount. I could now confirm again that I do not need to add any redirect URI in xs-security.json and still the approuter can successfully authenticate against the XSUAA a) in the deployed version on BTP and b) via approuter running on localhost. 
I just try to understand if localhost is also always allowed without the need of whitelisting it in the redirect URI, because currently it seems so, but this contradicts the documentation.
Only for the Business Application Studio I need to explicitly add the URI to redirect URI in order to authenticate properly when running locally on BAS.

**Comment by MichaelPShea** [comment]
Discussed this issue with SMUX directly. But basically this is the issue:

When developing locally, localhost is always allowed unless you configure something different in the local environment variable uaa.redirect.uri.domains. In the cloud landscapes, localhost and *.cfapps are always allowed. For both local and cloud developments, the values you set in the xs-security.json also apply.
I'll see if I can update this documentation to inlcude this information.
