### ISSUE TITLE
btpcli issue

### ISSUE THREAD

**Issue by gflex** [SAP-docs/btp-cloud-platform#172]
### Issue description

btpcli comes with incorrect permissions

Downloaded the file and extracted using tar:
```
get -q -O btpcli.tar.gz --no-cookies --header "Cookie: eula_3_1_agreed=tools.hana.ondemand.com/developer-license-3_1.txt; path=/;" -S https://tools.hana.ondemand.com/additional/btp-cli-linux-amd64-latest.tar.gz &&
tar xf btpcli.tar.gz && sudo mv linux-amd64/btp /usr/local/bin/ 
```
then ran ls and saw the huge UID and GID which surpass some linux distros default limits.
```
root@90c50ca56fb9:/# ls -latr /usr/local/bin/btp
-rwxr-xr-x 1 1672090608 510800513 12190452 Jul 11 09:24 /usr/local/bin/btp

/usr/local/bin/btp --version
SAP BTP command line interface (client v2.49.0)
```
expected output:
```
root@90c50ca56fb9:/# ls -latr /usr/local/bin/btp
-rwxr-xr-x 1 root root 12190452 Jul 11 09:24 /usr/local/bin/btp
```
Please as the colleagues who produce the file to rectify.

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Account Administration Using the SAP BTP Command Line Interface (btp CLI)

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/account-administration-using-sap-btp-command-line-interface-btp-cli

**Comment by NHingerl** [comment]
Hi @gflex, I learned that you found a solution for the technical problem. 

So I'd consider this issue solved, because the request was about a code change, not documentation. 
If you desire any change in documentation, please re-open this ticket and specify the required change.

Just to document it here as well, this was the dev response:

> The problem is that tar by default preserves UID/GID from the build machines, which can vary depending on the machine used by xMake.
> (...)
> I see that you have already fixed your issue by reassigning the owner. Alternatively, you could use the additional flag -o while extracting to achieve the same or use a non-root user, see https://linux.die.net/man/1/tar.

**Comment by gflex** [comment]
yes, I found a solution to _my_ problem. Thanks for encouraging customers to finding ways for fixing SAP products flaws right from the tar archive.

**Comment by mgradl** [comment]
Hi @gflex,

thanks for bringing this issue to our attention. I agree that we have to fix this issue in the archive itself by "anonymizing" the tar entries, and we have already started to work on that. Nevertheless we wanted to provide a possible workaround if other users have the same issue, before we can ship the next release or provide a fixed version as hotfix. 

So, again, thanks for taking the time to report the issue!
