### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by jeffvc** [SAP-docs/btp-cloud-platform#174]
### Issue description

Given that Python 3.7 is no longer supported, will this be removed from the BTP build packs? Also, can instructions on how to reference specific versions of Python be published? The build packs provide all versions, from 3.7 to 3.10, so how to specify a specific version would be very helpful.

### Feedback Type (Optional)

other

### Page Title on SAP Help Portal (prefilled)

Developing Python in the Cloud Foundry Environment

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/developing-python-in-cloud-foundry-environment

**Comment by nikolasimeonov77** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by Joysie** [comment]
Hi @jeffvc,

Thank you for your feedback! 
With the latest update of SAP BTP, Python 3.7 is now **removed** from the documentation. See:  [Supported Versions](https://help.sap.com/docs/btp/sap-business-technology-platform/developing-python-in-cloud-foundry-environment#supported-versions)

To learn how to specify a particular **buildpack version** that contains the _Python version(s)_ you need, see:  [Specify a buildpack version in manifest.yml](https://help.sap.com/docs/btp/sap-business-technology-platform/tips-and-tricks-for-python-applications#loiob5e1c8244e594f53936b6406905c7937__specify_python_bp_version)

You can specify a specific **Python version** for your application in the **runtime.txt** file. For example:

`python-3.11.*` 

To see a full end-to-end Python tutorial, see: [Create an Application with Cloud Foundry Python Buildpack](https://developers.sap.com/tutorials/btp-cf-buildpacks-python-create.html)

Hope that helps! 🙂

Best regards,
Gergana
