### ISSUE TITLE
Difference between Free Tier vs. Always Free for Trial Accounts remains unclear to me

### ISSUE THREAD

**Issue by ECasio** [SAP-docs/btp-cloud-platform#177]
### Issue description

When I read the documentation it's yet unclear to me what that means for a BTP Trial account:https://help.sap.com/docs/btp/sap-business-technology-platform/trial-accounts-and-free-tier

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Trial Accounts and Free Tier

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/trial-accounts-and-free-tier

**Comment by nikolasimeonov77** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by nikolasimeonov77** [comment]
Hi @ECasio,
You can also read https://help.sap.com/docs/btp/sap-business-technology-platform/using-free-service-plans. Unlike the trial account, you can get CPEA (Cloud Platform Enterprise Agreement) and Pay-As-You-Go commercial model with free tier account. Furthermore, you can just move from a free tier to a paid productive account when you reach the boundaries of the limited resources. On the other side, when the trial account expires, it is automatically deleted and you need to request a new one for productive use.

**Comment by ECasio** [comment]
Hi @nikolasimeonov77,

yes but what is missing in the docu is that a these free tier or always free services have the same meaning for a trial account. That's what I am talking about. The docu doesn't clearly draw the line here. It's free if you have a contracted BTP account, just like certain movies and TV serieses are for free on Amazon Prime (if you paid for a normal amazon prime account).

**Comment by Madeline-Schaefer** [comment]
Hi @ECasio,

Thank you again for your feedback.

At the moment we are still working on adjustments in the documentation for exactly this topic. As soon as we finalize these changes and I have all existing and up-to-date information available, I'm happy to get in touch with you again.

Best regards,
Madeline

**Comment by nikolasimeonov77** [comment]
Hi all,
As there is nothing more to discuss, I'll close the issue for now.

@Madeline-Schaefer Please notify @ECasio when you have an updated version of the new document. You can also reopen the issue if you need to discuss more about this issue.

Thanks for you collaboration!

Nikola

**Comment by ECasio** [comment]
https://people.sap.com/eddi
