### ISSUE TITLE
Feedback for "Getting an Access Token for SAP Cloud Management Service APIs"

### ISSUE THREAD

**Issue by mameling** [SAP-docs/btp-cloud-platform#18]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/3670474a58c24ac2b082e76cbbd9dc19.html

Typo "SAPSAP Cloud Management service " -> should be "SAP Cloud Management service "

**Comment by dkorts1** [comment]
Thank you for your contribution.
This has been fixed.

**Comment by nikolasimeonov77** [comment]
The update is now published at https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/3670474a58c24ac2b082e76cbbd9dc19.html?version=Cloud.
