### ISSUE TITLE
Button "Export to cTMS" was renamed to "Export Commit"

### ISSUE THREAD

**Issue by gregorwolf** [SAP-docs/btp-cloud-platform#180]
### Issue description

The documentation mentions the Button "Export to cTMS" but in my BTP ABAP environment it seems that this button was renamed to "Export Commit":

<img width="895" alt="Screenshot 2023-09-20 at 10 56 56" src="https://github.com/SAP-docs/btp-cloud-platform/assets/2639535/0b7e3275-8adc-498a-9531-79f5591e7d2b">

The screenshot and text needs to be adjusted accordingly.

### Feedback Type (Optional)

outdated information

### Page Title on SAP Help Portal (prefilled)

How to Export Using SAP Cloud Transport Management

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/how-to-export-using-ctms?q=ctms

**Comment by nikolasimeonov77** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by YasminavanRooij** [comment]
We've changed the documentation accordingly. Thank you for your feedback!

**Comment by gregorwolf** [comment]
https://people.sap.com/gregorw
