### ISSUE TITLE
"No Title" in table of content

### ISSUE THREAD

**Issue by JenniferStamm** [SAP-docs/btp-cloud-platform#183]
### Issue description

It looks like the page title is 'Get Events', but it's not displayed in the table of content:
![image](https://github.com/SAP-docs/btp-cloud-platform/assets/7091280/759dbbcb-a5f0-4201-9570-2b0de1f1521e)

### Feedback Type (Optional)

other

### Page Title on SAP Help Portal (prefilled)

Using the Events Service APIs

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/get-events

**Comment by Peteva** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by MichaelGlaun** [comment]
@JenniferStamm, thank you very much for your feedback. The issue should be resolved with the next update of the documentation on the SAP Help Portal.

**Comment by MichaelGlaun** [comment]
@JenniferStamm, issue is fixed. Confirmed now in today's update of the SAP Help Portal. Thanks again for your report. :)
