### ISSUE TITLE
Creation of job template failed: Object ZNE_TEST_JC must not be used (due to ABAP language version)

### ISSUE THREAD

**Issue by Neil057** [SAP-docs/btp-cloud-platform#184]
### Issue description

My Cloud System: SAP S/4HANA CLOUD 2308
I follow the sample code to create job catalog entry and job template,
but it failed to create 'Job Template' ,Error msg as Topic description.

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Creating the Job Template

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/creating-job-template

**Comment by Peteva** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by YasminavanRooij** [comment]
Hi Neil, 
the documentation is correct, but this is a backend issue that our developers have to take a look at. I discussed this with them. Please open an incident with SAP BTP ABAP environment so we can take a closer look. Thank you!
