### ISSUE TITLE
Wrong link referencing documentation of Web-IDE instead of the one for BTP

### ISSUE THREAD

**Issue by joergdw** [SAP-docs/btp-cloud-platform#186]
### Issue description

The text `For more information about the MTA development descriptor, see [Inside an MTA Descriptor](https://help.sap.com/viewer/825270ffffe74d9f988a0f0066ad59f0/CF/en-US/26d41dcc35ab4c458c2e3714ec422b80.html).` References in the end the URL `https://help.sap.com/docs/web-ide/sap-web-ide-full-stack/inside-mta-descriptor`. This is a change to another product's documentation that supports different values in its mta-descriptors.

Correct would be to redirect instead to `https://help.sap.com/docs/btp/sap-business-technology-platform/defining-multitarget-application-deployment-descriptors-for-cloud-foundry`.

### Feedback Type (Optional)

linking

### Page Title on SAP Help Portal (prefilled)

Defining Multitarget Application Development Descriptors

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/defining-multitarget-application-development-descriptors?version=Cloud

**Comment by Peteva** [comment]
Thank you for your feedback! We'll look into it and contact you if we have further questions.

**Comment by christiansavchev** [comment]
The documentation has been updated with the proposed corrections as of 18.10.2023.
