### ISSUE TITLE
"Multi-cloud foundation" is not explained in Basic Platform-Concepts

### ISSUE THREAD

**Issue by BaerbelW** [SAP-docs/btp-cloud-platform#188]
### Issue description

I noticed that the term "multi-cloud foundation" is used without an explanation of what it is in the 2nd paragraph. Perhaps elaborate a bit on that?

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

Basic Platform Concepts

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/btp-basic-platform-concepts

**Comment by annawenger20** [comment]
Thanks for your valuable contribution! Here's a better explanation, I hope this makes it clearer. The update will be made available with the next release on SAP Help Portal.  

SAP Business Technology Platform is built on a multi-cloud foundation, which lets you choose from different infrastructures and runtimes. The services and solutions of SAP BTP are available on multiple cloud infrastructure providers, and it supports different runtimes, such as Cloud Foundry, ABAP, and Kyma, as well as multiple different regions, and a broad choice of programming languages. 

The counterpart the multi-cloud foundation of SAP BTP is the SAP BTP Neo environment. To access the documentation for the Neo environment, see [SAP BTP, Neo environment](https://help.sap.com/viewer/ea72206b834e4ace9cd834feed6c0e09/Cloud/en-US). For migration information from the SAP BTP Neo environment to the multi-cloud foundation, see Migrating from the SAP BTP Neo Environment to the Multi-Cloud Foundation.

**Comment by BaerbelW** [comment]
https://people.sap.com/baerbelwinkler
