### ISSUE TITLE
Wrong hyperlink

### ISSUE THREAD

**Issue by biscimus** [SAP-docs/btp-cloud-platform#190]
### Issue description

Hyperlink to [Domain Modeling] is wrong.

### Feedback Type (Optional)

outdated information

### Page Title on SAP Help Portal (prefilled)

Best Practices

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/best-practices-e4a7559baf9f4e4394302442745edcd9?locale=en-US

**Comment by annawenger20** [comment]
Thank you for spotting this - we'll correct the link and let you know when it's visible on SAP Help Portal.

**Comment by renejeglinsky** [comment]
Thanks @biscimus for spotting this and letting us know. I did the following:
1. Implemented a [proper redirect](https://github.com/cap-js/docs/commit/43519ec24bba506a99017f8b5f61bb9e70615528) on cap.cloud.sap
2. Fixed the links on that page.

Both are to be delivered in the upcoming releases.
