### ISSUE TITLE
Please make it clear if the reference to "S/4HANA Cloud" is for the public edition and/or private edition

### ISSUE THREAD

**Issue by ssimsekler** [SAP-docs/btp-cloud-platform#191]
### Issue description

It's quite common in SAP documentation to mention "SAP S/4HANA Cloud" while the intention is only for the "public edition". For customers and partners, this is not ideal as it causes wasted time until they figure out the exact intention from the content.

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

Register an SAP S/4HANA Cloud System in a Global Account in SAP BTP

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/register-sap-s-4hana-cloud-system-in-global-account-in-sap-btp

**Comment by annawenger20** [comment]
Thanks a lot for your feedback. We'll look into it and get back to you with an update.

**Comment by ekaterina-mitova** [comment]
Hi @ssimsekler, 

You are right, I will adapt the documentation adding "public edition" to SAP S/4HANA Cloud. 
Thank you so much for pointing this out!

**Comment by ekaterina-mitova** [comment]
I've done the changes, they will be visible with the next release of the documentation.
