### ISSUE TITLE
"Java out of memory behaviour" mentions volume, but there is no volume service

### ISSUE THREAD

**Issue by calle2010** [SAP-docs/btp-cloud-platform#193]
### Issue description

https://help.sap.com/docs/btp/sap-business-technology-platform/java-out-of-memory-behavior?q=volume

To my knowledge there is no volume service available to customers and partners. If there is then a link to the respective part of the documentation should be provided.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Java Out Of Memory Behavior

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/java-out-of-memory-behavior?q=volume

**Comment by annawenger20** [comment]
Thank you for your feedback - we will look into this and get back to you.

**Comment by Joysie** [comment]
Hi @calle2010,

Thank you for your comment and feedback! You're right, there is no customer-available volume service.

So I removed this misleading part from the documentation. If some day we provide such a service, I'll update the topic with the relevant information and link.

Best regards,
Gergana

**Comment by calle2010** [comment]
https://people.sap.com/christian.schaefer2016
