### ISSUE TITLE
Service Components for BTP not visible

### ISSUE THREAD

**Issue by I038871** [SAP-docs/btp-cloud-platform#194]
### Issue description

https://help.sap.com/docs/btp/sap-business-technology-platform/support-components#service-components- We do not see Service Components in this link which was available for customers and we used to refer the customers to this page to create technical incidents. I cleared cache to see if that was the issue, but no. That isn't and the service component list (originally listed) is missing.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Support Components

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/support-components

**Comment by Peteva** [comment]
Thank you for your feedback, we will look into it and get back to you if we have any questions.

**Comment by nikolasimeonov77** [comment]
Hi @I038871,
I've addressed the issue and hope the Dev team will process it as soon as they can.

Thanks!

Nikola

**Comment by I038871** [comment]
Thank you for looking into the query & taking this forward. Rgds, Parvathi

**Comment by I038871** [comment]
Sorry, I clicked on "close with comment" by mistake. Please continue to look into the issue for a fix. Thnx & rgds, Parvathi

**Comment by nikolasimeonov77** [comment]
Hi @I038871,
The issue is fix now. See https://help.sap.com/docs/btp/sap-business-technology-platform/support-components?version=Cloud.
