### ISSUE TITLE
Outdated Java versions

### ISSUE THREAD

**Issue by GoeLin** [SAP-docs/btp-cloud-platform#197]
### Issue description

Hi,
It might be that the reported Java versions are outdated. 
I don't know about the actual defaults in the Java build pack, but build pack on 
SapMachine 11 might already be out-of-support, and surely will be so soon, so the default should be 17.
Maybe it also already supports Java 21 which has arrived in 9/2023.
Maybe you want to double check, and if changes only will happen soon you could mention so in the doku.
Best regards, Goetz, PO of SapMachine.

The SAP Java Buildpack (sap_java_buildpack) supports the following Java versions:

Java 8 – default version when you use SAP JVM (it provides a JRE with Java 8)
Java 11 – default version when you use SapMachine (it provides a JRE with Java 11)
Java 17 – possible version when you use SapMachine (it provides a JRE with Java 17)

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Developing Java in the Cloud Foundry Environment

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/developing-java-in-cloud-foundry-environment

**Comment by Peteva** [comment]
Hi @GoeLin, thank you for your feedback. We will look into it and get back to you if we need more information.

**Comment by GoeLin** [comment]
Hi,

I can not give you more input than that SapMachine 11 support ends 12/2024.
You need to check with the sap_java_buildpack people.

Best, Goetz.

**Comment by Joysie** [comment]
Hi @GoeLin ,

Thank you for your query! 
I double-checked with SAP Java Buildpack team - the current Java versions (including the default one) are correct. When that status changes, I'll update the documentation as well.

Best regards,
Gergana
