### ISSUE TITLE
Feedback for "Assign Roles in the Kyma Environment"

### ISSUE THREAD

**Issue by dvankempen** [SAP-docs/btp-cloud-platform#20]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/148ae38b7d6f4e61bbb696bbfb3996b2.html?locale=en-US

This role does not give access to **Kyma system Namespaces** published on non-SAP site and grants only read access to **AddonsConfigurations** published on non-SAP site because administration of these resources is restricted to Kyma system admins.

Both references return 404

**Comment by klaudiagrz** [comment]
Hi @dvankempen ! 👋  

Thank you for spotting that! Both links are already fixed in the internal version and will be published to production with takt 13b.

**Comment by Peteva** [comment]
The update is now published at [https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/148ae38b7d6f4e61bbb696bbfb3996b2.html?locale=en-US](https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/148ae38b7d6f4e61bbb696bbfb3996b2.html?locale=en-US)
