### ISSUE TITLE
Help when certificate type is not supported

### ISSUE THREAD

**Issue by schiwekM** [SAP-docs/btp-cloud-platform#200]
### Issue description

Hi colleagues,

the docu page is overall quite helpful - however one thing I stumbled over is, that SF API is not supporting the certificates with a .pem file extension and throws the issue like `The format of the provided certificate 'SF_Integration.pem' is not supported. Supported formats are: p12, pfx. `

https://answers.sap.com/questions/13980793/sap-btp-destination-using-client-certificate-authe.html explains how to resolve the issue, but I would like to see that either SF directly supports the .pem format or that the docu mentions the workaround and in case the issue shows up. 

BR,
Marten

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Using Mutual Transport Layer Security (mTLS)

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/using-mutual-transport-layer-security-mtls

**Comment by nikolasimeonov77** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by ekaterina-mitova** [comment]
Hi @schiwekM, 
Thank you for you feedback. We will work on updating our documentation and we will forward this issue to the team responsible so the .pem format is added to the supported formats. It may take some time to do that. Once the format is supported, I will update the documentation respectively.

**Comment by ekaterina-mitova** [comment]
Hi @schiwekM,

The documentation is updated now to include not only .pem format but also .p12. See [Using Mutual Transport Layer Security (mTLS)](https://help.sap.com/docs/btp/sap-business-technology-platform/using-mutual-transport-layer-security-mtls).

And the .pem format has been added to the supported formats. You can check when it will be released at https://github.com/SAP/cloud-sdk-js/pull/4473.

**Comment by schiwekM** [comment]
Hi @ekaterina-mitova,
much appreciated for the improved documentation and taking care that cloud sdk supports the format.
Thanks.
BR, Marten
