### ISSUE TITLE
Outdated link

### ISSUE THREAD

**Issue by georgbischoff** [SAP-docs/btp-cloud-platform#201]
### Issue description

The link to **Creating Service Keys** is outdated and should be replaced:
- Current link: [Create Service Keys Using the Cockpit](https://help.sap.com/docs/btp/sap-business-technology-platform/create-service-keys-using-cockpit)
- New link: [Creating Service Keys in Cloud Foundry](https://help.sap.com/viewer/09cc82baadc542a688176dce601398de/Cloud/en-US/6fcac08409db4b0f9ad55a6acd4d31c5.html)

### Feedback Type (Optional)

linking

### Page Title on SAP Help Portal (prefilled)

Creating Service Keys

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/creating-service-keys

**Comment by nikolasimeonov77** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by danielforsap** [comment]
Hi @georgbischoff,
There is a redirection on the page. We can't delete that page because it is being used in many docs. 
Kind regards,
Daniel

**Comment by danielforsap** [comment]
Hi,
Changed the link per feedback.
Will be released with T12b.
Thank you for your contribution @georgbischoff.
