### ISSUE TITLE
Typo in Caution Box

### ISSUE THREAD

**Issue by hottek** [SAP-docs/btp-cloud-platform#206]
### Issue description

At the bottom of the page, inside the box which is headlined with 'Caution' there is a typo. I believe it should say 'The tutorial group' instead of 'The turorial group'.

### Feedback Type (Optional)

spelling or grammar

### Page Title on SAP Help Portal (prefilled)

Developing and Operating SaaS Applications

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/developing-and-operating-saas-applications

**Comment by Peteva** [comment]
@hottek, Thank you for your feedback! We'll look into it and keep you updated on the progress.

**Comment by sarahbaczyk** [comment]
@hottek Thanks for the contribution. You will be able to see the change on SAP Help Portal after the next content update.

**Comment by hottek** [comment]
https://people.sap.com/lukaspr
