### ISSUE TITLE
Not able to access SAP Warehouse Robotics with my free account and the message directs me to this page that does not have enough details

### ISSUE THREAD

**Issue by rrjoseph** [SAP-docs/btp-cloud-platform#213]
### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Getting a Global Account

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/getting-global-account?version=Cloud#free-tier

**Comment by rrjoseph** [comment]
Additionally - this is the page that led me to this help page:
Can't Find a Service or a Plan?
While using a trial account on SAP BTP, you are entitled to use a specific set of services for free.

You can view the available trial services in the [SAP Discovery Center](https://discovery-center.cloud.sap/viewServices?showFilters=true&commercialModel=trial&provider=all&regions=all).

To access additional services and plans, you can use SAP BTP free tier, which facilitates a smooth transition to production use after trying out SAP BTP. [Learn more about free tier](https://help.sap.com/docs/btp/sap-business-technology-platform/getting-global-account#free-tier)

**Comment by Peteva** [comment]
Thank you for your feedback! We will look into it and get back to you if we have additional questions.

**Comment by nikolasimeonov77** [comment]
Hi @rrjoseph,
SAP Warehouse Robotics doesn’t support trial use. Customers need to buy a license to use SAP Warehouse Robotics. 
Here is the documentation on Help Portal for SAP Warehouse Robotics: https://help.sap.com/docs/WAREHOUSE_ROBOTICS.

**Comment by rrjoseph** [comment]
Nikola,

Thanks for your response. I would prefer that the Robotics help
documentation be updated to state this for clarity.

Regards,
Ranjith

Ranjith Joseph

Engagement Manager

859.803.7071 | ***@***.***

My Supply Chain Group LLC  | www.mysupplychaingroup.com
[image: image.png]

**Comment by nikolasimeonov77** [comment]
Hi @rrjoseph,
Thanks for your feedback. We've addressed your feedback to the responsible author.

**Comment by rrjoseph** [comment]
Hi Nikola,
Thank you for your response.


Ranjith Joseph

Engagement Manager

859.803.7071 | ***@***.***

My Supply Chain Group LLC  | www.mysupplychaingroup.com
[image: image.png]
