### ISSUE TITLE
Add a sub-page on how to enable the usage of the Manage API Snapshots app

### ISSUE THREAD

**Issue by hottek** [SAP-docs/btp-cloud-platform#214]
### Issue description

I think it would be beneficial for users to be able to know which business role template or business catalog ID they need in order to access the Manage API Snapshots app. Maybe a page similar to [Enable Usage of the ABAP Test Cockpit Configurator App](https://help.sap.com/docs/btp/sap-business-technology-platform/enable-usage-of-abap-test-cockpit-configurator-app)?

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

Manage API Snapshots

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/manage-api-snapshots

**Comment by nikolasimeonov77** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by YasminavanRooij** [comment]
Hi everyone, 

I've added the subpage. Thank you for the suggestion!

Best regards, 

Yasmina
