### ISSUE TITLE
Incorrect information, Discovery Center is not listing all BTP services

### ISSUE THREAD

**Issue by piejanssens** [SAP-docs/btp-cloud-platform#215]
### Issue description

I'm unable to locate "SAP SuccessFactors Work Zone" or "SAP Cloud ALM"

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

Solutions and Services

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/solutions-and-services?version=Cloud

**Comment by nikolasimeonov77** [comment]
Hi @piejanssens,
This repository is only used to review feedback on documentation. Please use other more appropriate channels to report problems with SAP Discovery Center (such as the [SAP Community Q&A](https://answers.sap.com/) and the [SAP Support Portal](https://support.sap.com/)). See also our [Dos and Don'ts](https://help.sap.com/products/open-documentation-initiative/contribution-guidelines/dos-and-donts.html).

**Comment by nikolasimeonov77** [comment]
Hi @piejanssens,
I can also redirect your feedback to the SAP Discovery Center developers and leads if you provide details what services are missing?

**Comment by nikolasimeonov77** [comment]
Hi @piejanssens,
I've just the following responses for these services from their leads:
"SAP Cloud ALM itself isn’t an SAP BTP service. 
There’s only an SAP BTP service that belongs to SAP Cloud ALM, the SAP Cloud ALM, memory extension service, and it is listed on SAP Discovery Center."

"SuccessFactors Work Zone is a SuccessFactors SaaS solution and therefore is not in SAP Discovery Center".

These are the links to the services' landing pages:
SAP Success Factors Workzone: https://help.sap.com/docs/SAP_SUCCESSFACTORS_WORK_ZONE?locale=en-US 
SAP Cloud ALM: https://help.sap.com/docs/cloud-alm?locale=en-US
