### ISSUE TITLE
How can I stop the Feedback popup?

### ISSUE THREAD

**Issue by NSXBLUE** [SAP-docs/btp-cloud-platform#218]
### Issue description

Everytime I hit a page in help.sap.com the annoying feedback animation popup comes up and interrupts my viewing. I click the DO NOT SHOW THIS AGAIN checkbox, but it still comes up. Please help as this is VERY frustrating.

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Cloud Foundry Environment

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/9c7092c7b7ae4d49bc8ae35fdd0e0b18.html

**Comment by Peteva** [comment]
Hello @NSXBLUE,
Thank you for your feedback. We will look into it.

**Comment by nikolasimeonov77** [comment]
It seems that the issue is fixed now. Thanks for the valuable feedback!
