### ISSUE TITLE
Feedback for "Authentication Type JSON File"

### ISSUE THREAD

**Issue by dvankempen** [SAP-docs/btp-cloud-platform#22]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/543fbd6103d746f19c410dc2092d6f5e.html?locale=en-US

Note the trailing comma 
makes this JSON invalid

{
   "systemName":"MY_SYSTEM",
   "technicalUser":"technicalonboarder",
}

{
   "systemName":"MY_SYSTEM",
   "technicalUser":"technicalonboarder"
}

**Comment by Peteva** [comment]
Hi @dvankempen,
Thank you for your feedback! The documentation has been updated. You will be able to see the change on SAP Help Portal after the next content update.
