### ISSUE TITLE
broken link in page https://help.sap.com/docs/btp/sap-business-technology-platform/managed-application-router?version=Cloud

### ISSUE THREAD

**Issue by bvarwig** [SAP-docs/btp-cloud-platform#221]
### Issue description

on the page there is a broken link: 
![image](https://github.com/SAP-docs/btp-cloud-platform/assets/8438658/5db8e960-f0e6-4e98-b397-f13cd99b534b)
-------------------------------------------------------------------------------------------->

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Managed Application Router

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/managed-application-router?version=Cloud

**Comment by SarahErdmann** [comment]
Hello @bvarwig!  Thanks for pointing this out.  We fixed the broken link.  You will be able to see this change on SAP Help Portal after the next content update.

**Comment by nikolasimeonov77** [comment]
I am closing this GitHub issue as the link is fixed.
