### ISSUE TITLE
Unable to access links for "Use" on "Continuous Integration and Delivery (CI/CD)" page

### ISSUE THREAD

**Issue by llouw-drs** [SAP-docs/btp-cloud-platform#222]
### Issue description

Unable to access link at [Continuous Integration and Delivery (CI/CD](https://help.sap.com/docs/btp/sap-business-technology-platform/continuous-integration-and-delivery-ci-cd#use). All of them say 404 page not found.

![Screenshot 2024-04-17 at 8 29 34 AM](https://github.com/SAP-docs/btp-cloud-platform/assets/137168549/8245eac1-0ef5-4e69-8287-4665d8d7ff5e)

### Feedback Type (Optional)

linking

### Page Title on SAP Help Portal (prefilled)

Continuous Integration and Delivery (CI/CD)

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/continuous-integration-and-delivery-ci-cd

**Comment by llouw-drs** [comment]
Thanks.

This is the links that do not work:
![Screenshot 2024-04-18 at 8 38 04 AM](https://github.com/SAP-docs/btp-cloud-platform/assets/137168549/8fff0076-0a6f-463f-a50a-0c6ca753a429)

They all forward to the DRAFT versions of the pages which in return just gives a not found error.

**Comment by Madeline-Schaefer** [comment]
Thank you again for your feedback. 

The links were fixed and the documentation will be updated with the next release.

Kind regards,
Madeline
