### ISSUE TITLE
Broken link in Implementing an Outbound Service Call to SAP S/4HANA Cloud

### ISSUE THREAD

**Issue by mmitoraj** [SAP-docs/btp-cloud-platform#226]
### Issue description

In the [Implementing an Outbound Service Call to SAP S/4HANA Cloud](https://help.sap.com/docs/btp/sap-business-technology-platform/implementing-outbound-service-call-to-sap-s-4hana-cloud?version=Cloud) document, the link in the Related Information section to the [Tutorial: Create Business Partner in SAP S/4HANA Cloud using ABAP Environment Data](https://help.sap.com/docs/link-disclaimer?site=https%3A%2F%2Fdevelopers.sap.com%2Ftutorials%2Fabap-environment-business-partner.html) is broken.

Please update the link.

### Feedback Type (Optional)

linking

### Page Title on SAP Help Portal (prefilled)

Implementing an Outbound Service Call to SAP S/4HANA Cloud

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/implementing-outbound-service-call-to-sap-s-4hana-cloud?version=Cloud

**Comment by nikolasimeonov77** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by nikolasimeonov77** [comment]
The link is deleted in the topic and the changes will be available with the next release.
