### ISSUE TITLE
Broken link in Tutorial Overview

### ISSUE THREAD

**Issue by mmitoraj** [SAP-docs/btp-cloud-platform#227]
### Issue description

In the [Tutorial Overview](https://help.sap.com/docs/btp/sap-business-technology-platform/tutorial-overview?state=DRAFT&version=Cloud) document, the link to [Create Business Partner in S/4HANA Cloud Using ABAP Environment Data](https://help.sap.com/docs/link-disclaimer?site=https%3A%2F%2Fhelp.sap.com%2Fdocs%2Flink-disclaimer%3Fsite%3Dhttps%253A%252F%252Fdevelopers.sap.com%252Ftutorials%252Fabap-environment-business-partner.html) is broken.

Please update or remove the link.

### Feedback Type (Optional)

linking

### Page Title on SAP Help Portal (prefilled)

Tutorial Overview

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/tutorial-overview?state=DRAFT&version=Cloud

**Comment by nikolasimeonov77** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by sarahbaczyk** [comment]
Thank you for your feedback. 

Unfortunately, there is no newer link available, so I deleted the one mentioned and will close this issue.
