### ISSUE TITLE
How to map Application URLs example BTP SAAS product Resource Management in identity provider --> Create new application

### ISSUE THREAD

**Issue by gkumar-5** [SAP-docs/btp-cloud-platform#228]
### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Manually Establish Trust and Federation Between SAP Authorization and Trust Management Service and Identity Authentication

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/7c6aa87459764b179aeccadccd4f91f3.html

**Comment by Peteva** [comment]
Dear @gkumar-5, 
Thank you for your feedback. We will look into it and get back to you if we have questions.

**Comment by MichaelPShea** [comment]
Hi @gkumar-5, 
I don't understand what your feedback is.  Are you saying you want an example of how to map application URLs? This documentation is only about how to establish trust between BTP and an identity provider. Nor is this our recommended method for establishing trust. We would prefer you to use OIDC: https://help.sap.com/docs/btp/sap-business-technology-platform/establish-trust-and-federation-between-uaa-and-identity-authentication

**Comment by gkumar-5** [comment]
[C4P_BTP_SSO.docx](https://github.com/user-attachments/files/15510623/C4P_BTP_SSO.docx)

**Comment by MichaelPShea** [comment]
Hi @gkumar-5 ,
If I understand your issue correctly, there is no need for any special URL mapping. The subscribed app runs in your subaccount. As long as it is configured to use SAP Authorization and Trust Management service (XSUAA), when your user attempts to log on, XSUAA will forward the user to SAP Cloud Identity services for authentication no the basis of this trust configuration. If the user successfully authenticates, SAP Cloud Identity returns a SAML token, which XSUAA accepts and the user can access the resource.

**Comment by MichaelPShea** [comment]
Closing.
