### ISSUE TITLE
Feedback for "Authentication Type JSON File"

### ISSUE THREAD

**Issue by dvankempen** [SAP-docs/btp-cloud-platform#23]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/543fbd6103d746f19c410dc2092d6f5e.html?locale=en-US

Information about the SuccessFactors technical users is missing. 
Is this user automatically created on the SuccessFactors side during provisioning? 
Does this require any action in the SuccessFactors Admin Center? 
Roles? Privileges?

**Comment by ekaterina-mitova** [comment]
Hi @dvankempen,
The technical user can be any user with the respective permissions. These permissions depend on the use case and the API you want to access. 
To find out which permission you need to assign to the technical user, go to [SAP API Business Hub](https://api.sap.com/products/SAPSuccessFactors/overview), find the SAP SuccessFactors API you want to access and from the **Overview** tab go to the **Documentation** section and open the **help.sap.com** link. There you find the right information for each API.

**Comment by ekaterina-mitova** [comment]
Hi @dvankempen,
You will be able to see the change on SAP Help Portal after the next content update.
