### ISSUE TITLE
List of SAP SuccessFactors API Servers - Link not working

### ISSUE THREAD

**Issue by frankmeertens** [SAP-docs/btp-cloud-platform#230]
### Issue description

The link for the list of the SAP SuccessFactors API Servers is not working.

Link in page: https://help.sap.com/docs/SAP_SUCCESSFACTORS_PLATFORM/28bc3c8e3f214ab487ec51b1b8709adc/af2b8d5437494b12be88fe374eba75b6.html?version=LATEST&locale=en-US 

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Using Mutual Transport Layer Security (mTLS)

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/using-mutual-transport-layer-security-mtls

**Comment by Peteva** [comment]
Hi @frankmeertens, thank you for you feedback!
The documentation has been updated and the link now points to: https://help.sap.com/docs/SAP_SUCCESSFACTORS_PLATFORM/9f5f060351034d98990213d077dab38a/af2b8d5437494b12be88fe374eba75b6.html?version=latest
The change will be available on the SAP Help Portal with the next update.
