### ISSUE TITLE
Name to be changed

### ISSUE THREAD

**Issue by Dhawal-Joshi** [SAP-docs/btp-cloud-platform#235]
### Issue description

Name of API Business Hub has been rebranded to SAP Business Accelerator Hub . The URL https://help.sap.com/docs/btp/sap-business-technology-platform/authorization-and-trust-management-rate-limiting still refers it as API Business Hub

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Rate Limiting

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/authorization-and-trust-management-rate-limiting

**Comment by MichaelPShea** [comment]
Fixed in 2410a. Thanks for the catch!
