### ISSUE TITLE
Wrong property name logoutPath -> logoutEndpoint

### ISSUE THREAD

**Issue by mdudushka** [SAP-docs/btp-cloud-platform#236]
### Issue description

Hello,

In the table with the properties for the [logout configuration](https://help.sap.com/docs/btp/sap-business-technology-platform/logout) it's written `logoutPath` and in the rest of the document is `logoutEndpoint`. 

### Feedback Type (Optional)

outdated information

### Page Title on SAP Help Portal (prefilled)

logout

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/logout

**Comment by SarahErdmann** [comment]
Thank you for your feedback! You're right, the correct property name is `logoutEndpoint`. The correction will appear in the next update of the documentation.
