### ISSUE TITLE
Application Security Descriptor Configuration Syntax is missing Role Collection configuration

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/btp-cloud-platform#237]
### Issue description

Hi,

the chapter describing the xs-security.json syntax does not cover role collections. There is an example how to include role collections available here: https://help.sap.com/docs/btp/sap-business-technology-platform/create-role-collections-with-predefined-roles

But it would be nice, if the role collection part would also be described in the general reference for the Application Security Descriptor and not only in the Tasks on Demand section. It would also be nice to describe all elements of the role collection definition if there are more then the ones used in the example.

Kind regards,
Sebastian

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Application Security Descriptor Configuration Syntax

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/application-security-descriptor-configuration-syntax

**Comment by sebastianesch** [comment]
Actually I just noticed, that the role-collection information is already there but not included in the example at the top of the page where you can navigate to the different sections. I did not notice the point "role-collection" in the right navigation ("On this page").

**Comment by PlamiIG** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by mar-blu** [comment]
Hello Sebastian,

I am going to look into your request.

For the time being, I recommend to use the blog on the [Authorization and Trust Management product page](https://help.sap.com/docs/authorization-and-trust-management-service). Blog: https://community.sap.com/t5/technology-blogs-by-sap/creating-role-collections-in-sap-btp-using-the-new-role-collections/ba-p/13404427

**Comment by mar-blu** [comment]
Your suggestion to include the role-collection example into the first central example makes sense. However, such a change has low priority. 

I created a related backlog item. See https://jira.tools.sap/browse/SECDOC-1931

**Comment by mar-blu** [comment]
I created a related backlog item. See https://jira.tools.sap/browse/SECDOC-1931

**Comment by mar-blu** [comment]
The "role-collections" example will be available with an upcoming help portal delivery.
