### ISSUE TITLE
Broken Link - "Using GACD" in Deploying Content with Generic Application Content Deployment

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/btp-cloud-platform#243]
### Issue description

In the section [Supported Services](https://help.sap.com/docs/btp/sap-business-technology-platform/content-deployment#supported-service-offerings), the link [Using GACD](https://help.sap.com/docs/SAP_CP_BUS_REUSE_SERVICE_BL/9d9c6578dd284b7491e2b6ceb1395329/f4a898bd0f9b4619940dd049c5328ee4.html?locale=en-US) is not available for external users.

### Feedback Type (Optional)

linking

### Page Title on SAP Help Portal (prefilled)

Deploying Content with Generic Application Content Deployment

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/content-deployment?version=Cloud

**Comment by PlamiIG** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by alisa-dermen** [comment]
Thank you for making us aware of this issue. The problem is solved and the change will be applied on SAP Help Portal with the next content update.
