### ISSUE TITLE
All the embedded links seems to be expired

### ISSUE THREAD

**Issue by adminRoboxa** [SAP-docs/btp-cloud-platform#245]
### Issue description

https://help.sap.com/docs/btp/sap-business-technology-platform/concepts?state=DRAFT&version=Cloud#system-landscape%2Faccount-model

https://help.sap.com/docs/btp/sap-business-technology-platform/maintain-solution?version=Cloud

all the embedded links are expired

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Order and Provide

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/saas-apps-order-and-provide#loio35b5acbb32024aa6b90a22e9f957a9f6

**Comment by PlamiIG** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by sarahbaczyk** [comment]
Thank you for the feedback. Unfortunately, I cannot reach all colleagues with the necessary information to update all the links at the moment. For this reason, I will get back to the issue next week.

**Comment by sarahbaczyk** [comment]
I contacted the UA currently working on this topic, though she is out of office and will be back next week.
I did click through all the links in 'order and provide' though, and they did work for me.

**Comment by nikolasimeonov77** [comment]
Hi @sarahbaczyk,
The links are broken as reported becasue they don't open externally.

**Comment by nikolasimeonov77** [comment]
Hi @adminRoboxa,
The links are now fixed and will be published with the next release for 2412a.

Thanks for spotting them!

SIncerely,
Nikola
