### ISSUE TITLE
Documentation: CF existing service

### ISSUE THREAD

**Issue by whydrae** [SAP-docs/btp-cloud-platform#248]
In the `resources` section of the Multitarget Application Structure documentation, I found the following mistake (https://github.com/SAP-docs/btp-cloud-platform/blob/main/docs/30-development/resources-9e34487.md?plain=1#L138):

_То indicate that the (named) service exists, without managing its lifecycle, you define the service name by using the org.cloudfoundry.**managed**-service_

Should it be changed to: "you define the service name by using the org.cloudfoundry.**existing**-service"?

**Comment by PlamiIG** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by alisa-dermen** [comment]
Thanks for the contribution. You will be able to see the change on SAP Help Portal after the next content update.
