### ISSUE TITLE
Feedback for "Create an SAP SuccessFactors Extensibility Service Instance in the Kyma Environment"

### ISSUE THREAD

**Issue by dvankempen** [SAP-docs/btp-cloud-platform#25]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/f371f81d06c64a0fb507307c9ad24646.html?locale=en-US

Choose Namespaces from the left-hand side navigation and open the **default** Namespace.

Shouldn't this be the namespace where you want to access the extension?

**Comment by ekaterina-mitova** [comment]
Hello @dvankempen, 

You are right, it's not necessary to use the default namespace, you can create another namespace and use it instead. I will update the content in the next release. 
Thanks for noticing!

Best regards, 
Ekaterina
