### ISSUE TITLE
Feedback for "Add Organization Members Using the Cloud Foundry Command Line Interface"

### ISSUE THREAD

**Issue by mar-hol** [SAP-docs/btp-cloud-platform#26]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/1422a5daa53d498f9270727135005884.html?locale=en-US&version=Cloud

The parts mentioned in section "Context" is only applicable for customers on Feature Set A. 
For customer having Feature Set B as long as user is registered in SAP ID Service, you can use "cf set-org-role USERNAME ORG ROLE --origin sap.ids" command. At least it worked for me. Would you please clarify in more detail.

**Comment by renejeglinsky** [comment]
Hi @mar-hol ,

thanks a lot for your feedback. This seemed to be a limitation wrt CF CLI v6. As we are now supposed to use CF CLI v7 this shouldn't be an issue anymore. So I'd remove that misguiding text. Would that work for you?

The information is also contained in the topic [Supported Tools and Services When Using Custom Identity Providers for Platform Users[Feature Set A]](https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/94ef5154e384408796c035a82b043f82.html?version=Cloud) and there is also mentioned as restriction for CF CLI v6 in combination with Feature Set A. So the information would not be lost.

All the best.
René

**Comment by mar-hol** [comment]
Thanks for reaching out.  For clarification it would for sure help. Also maybe add as prerequisite for Feature set B that user for whom you want to assign a role in CF must exist in SAP ID service prior. Otherwise the command won't work (at least for me and unlike the cockpit where you can add org/space member without existing in SAP ID service => shadow users). Example: in BTP cockpit you can add "blabla@blabla.bla" as org/space member without any problem; using cf cli doesn't work for such an mail address)

**Comment by renejeglinsky** [comment]
I'll get back to you. Thanks again for your very valuable feedback.

**Comment by renejeglinsky** [comment]
Thanks @mar-hol. We've updated the documentation and will review before publication. Thanks a lot!

**Comment by mar-hol** [comment]
https://people.sap.com/mar-hol
