### ISSUE TITLE
Feedback for "Create an SAP SuccessFactors Extensibility Service Instance in the Kyma Environment"

### ISSUE THREAD

**Issue by mado0803** [SAP-docs/btp-cloud-platform#28]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/f371f81d06c64a0fb507307c9ad24646.html?locale=en-US

In "Procedure", Step 3, it should say: "Choose Namespaces from the left-hand side navigation and open the namespace in which you want to create a service instance."

**Comment by ekaterina-mitova** [comment]
Hi @mado0803, 

Yes, I have just updated this content. The changes will be there with the next release.

Best regards, 
Ekaterina
