### ISSUE TITLE
Feedback for "Extending SAP Marketing Cloud in the Cloud Foundry and Kyma Environment"

### ISSUE THREAD

**Issue by dvankempen** [SAP-docs/btp-cloud-platform#33]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/18bb3d945ab948b2ab2218b7869d0faf.html?locale=en-US

Page appears to document SAP S/4HANA Cloud not Marketing Cloud. Copy/paste?

**Comment by ekaterina-mitova** [comment]
Hi @dvankempen,
The documentation is correct. Even though it talks about SAP Marketing Cloud, you still use the SAP S/4HANA Cloud Extensibility service.
