### ISSUE TITLE
Feedback for "Create Service Instances Using kubectl"

### ISSUE THREAD

**Issue by SAP-Ayush** [SAP-docs/btp-cloud-platform#34]
Doc Reference: 

https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/b53be623b96547cdb5545577b1804ba9.html
https://kubernetes.io/docs/concepts/extend-kubernetes/service-catalog/

While creating service instance under spec `ServiceClassExternalName` and `ServicePlanExternalName` needs to be replaced with `clusterServiceClassExternalName` and `clusterServicePlanExternalName`.

cat <<EOF | kubectl apply -f -
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: {INSTANCE_NAME}
  namespace: {YOUR_NAMESPACE}
spec:
  clusterServiceClassExternalName: {SERVICE_NAME}
  clusterServicePlanExternalName: {PLAN_NAME}
  parameters:
    param-1: value-1
    param-2: value-2
EOF

**Comment by klaudiagrz** [comment]
Hello 👋 

The issue has already been fixed and the correct version is already visible on SAP Help Portal.

BR,
Klaudia

**Comment by SAP-Ayush** [comment]
https://people.sap.com/ayushbudhwani
