### ISSUE TITLE
Feedback for "Including SAP Systems in a Formation"

### ISSUE THREAD

**Issue by kuja11** [SAP-docs/btp-cloud-platform#35]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/68b04fa73aa740cb96ed380a85a4761a.html?locale=en-US&version=Cloud

This seems to be a new step in the help tutorial, since I don't recognize this since last visit in december. It would be awesome to know what this formation does more techincally. Could there be a section added to this?

And I am a bit worried this is chosen to be on global account level. I am SAP partner, working as external consultant for customers. Often we are not allowed to be assigned roles on global level, only subaccount. This troubles this setup, as the customer often would not know what to do and needs help. It seems complicating things having these things set on such high level.

**Comment by Peteva** [comment]
Hello @kuja11,
Thank you for your valuable feedback!
A formation is a logical grouping of SAP systems that can be extended in a single business scenario. Formations allow you to combine SAP systems, SAP applications, SAP BTP components, and runtimes to simplify the connectivity setup and to provide a unified view of all components required for the implementation of your extension scenario.
I have added this definition to the [Including SAP Systems in a Formation](https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/68b04fa73aa740cb96ed380a85a4761a.html?locale=en-US&version=Cloud).

The "Formations" tab in the SAP BTP cockpit has been around for some time. It was announced on May 7, 2020: [release note: Extensions - Grouping SAP Solutions in a Formation](https://help.sap.com/doc/eed1e41fe772463c8ce3fdfa1ca6e57f/Cloud/en-US/98bf747111574187a7c76f8ced51cfeb.html?date=all&sel1=Extensions&from=2020-05-01&to=2020-05-11url). 
There is also a "formation" entry in the SAP BTP [Glossary](https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/e67a1435bb571014b2758553897c59b6.html?version=Cloud).

**Comment by Peteva** [comment]
Hello @kuja11 ,
The idea to have systems connected on a global account level has two main reasons:
- Connect the system once to BTP and reuse it for extension applications residing in different subaccounts
- Limit the permissions to enable the system for extensibility to the global account admin only, and also considering the goal to provide access only to a specific API/set of APIs in future.
