### ISSUE TITLE
Feedback for "Regions and API Endpoints Available for the Cloud Foundry Environment"

### ISSUE THREAD

**Issue by QBYstefan** [SAP-docs/btp-cloud-platform#36]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/f344a57233d34199b2123b9620d0bb41.html?locale=en-US&version=Cloud

Hi,
when working in _SAP CPI_ in region eu10, is it necessary to provide all listed NAT IPs to 3rd party service providers?
Some months ago through testing, we found that only 3 of all the 27 IPs are used for SAP CPI outgoing data transfer. 
Is there an overview which NAT IPs belong to which BTP service or do you advise to always include all IPs regarding region eu10?

Kind regards
Stefan

**Comment by sdanter** [comment]
Thank you for reaching out @QBYstefan. I will look into this and get back to you.

**Comment by sdanter** [comment]
Hi @QBYstefan, 
 
the IPs listed for eu10 are all designated for use by CPI. Currently only 3 are active, but the remaining ones will be activated in the near future. 

For high availability and scalability reasons, there is more than one NAT gateway. It is therefore recommended to allowlist all of the IPs. 

All the best,
Stefan

**Comment by QBYstefan** [comment]
Thank you for the explanation, Stefan

**Comment by QBYstefan** [comment]
https://people.sap.com/qby-stefan
