### ISSUE TITLE
Feedback for "Using Kyma Eventing with SAP Event Mesh"

### ISSUE THREAD

**Issue by SAP-Ayush** [SAP-docs/btp-cloud-platform#37]
I was trying to bind Event Mesh in the Kyma environment with the deployed CAP application and after following this document I was not able to bind Event Mesh. It would be great if you can give an example on how to connect CAP application and update this documentation.
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/407d1266017f4b529b61665fa7408c41.html

**Comment by alexandra-simeonova** [comment]
Hi Ayush,

The documentation will be updated in the next couple of weeks when the Kyma 2.0 release rolls out. For other questions and more specific example, please also use the https://sap-btp.slack.com/archives/C0140PCSJ5Q channel.
