### ISSUE TITLE
Feedback for "Viewing a Change Log"

### ISSUE THREAD

**Issue by DerGuteWolf** [SAP-docs/btp-cloud-platform#38]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/ddd9de0bb41a4ce9a91ac9102b843e83.html

The reference to SAP Notes, where the text starts with "Start Transaction" is pointless for documentation for ABAP Environment, where NO transactions can be started. This holds true for both SAP Note references on this page.

**Comment by UmutAydin96** [comment]
The documentation has been updated and will be online with 2205 release.
