### ISSUE TITLE
Feedback for "Getting an Access Token for SAP Cloud Management Service APIs"

### ISSUE THREAD

**Issue by mbalsam82** [SAP-docs/btp-cloud-platform#39]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/3670474a58c24ac2b082e76cbbd9dc19.html

The "Prerequisites" section states

> Your global account admin has entitled at least **SAP ONE Service service plan** from the SAP Cloud Management service in your subaccount. See [SAP Cloud Management Service - Service Plans](https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/a508b724bf6d457ca7ac024b8e4b8457.html?) and [Managing Entitlements and Quotas Using the Cockpit](https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/c8248745dde24afb91479361de336111.html?).

However, this service plan doesn't seem to exist and isn't mentioned in the referenced child page either: https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/a508b724bf6d457ca7ac024b8e4b8457.html

**Comment by danielforsap** [comment]
Hello @mbalsam82 

> https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/3670474a58c24ac2b082e76cbbd9dc19.html
> 
 
Hello @mbalsam82 ,

The correct sentence should be:
"Your global account admin has entitled at least one of the plans for the SAP Cloud Management service in your subaccount."
In the linking documentation, you can find the relevant plans for that service.
I have fixed the sentence in the documentation.

Thank you for your contribution,
Daniel
