### ISSUE TITLE
Feedback for "Create Roles for Applications Using Existing Role Templates"

### ISSUE THREAD

**Issue by i801193** [SAP-docs/btp-cloud-platform#41]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/2670fd27fc804ad99313385711d644f6.html?locale=en-US&version=Cloud

Is SAP delivering roles or roles templates?
If SAP deliver only roles then documentaion should be updated accordingly

**Comment by MichaelPShea** [comment]
Hi i801193, 

SAP does indeed deliver roles and role templates. The application developer defines scopes and attributes and bundles them into roles and role templates. If the roles have attributes, the admin or developer can create different versions of these roles with different values for the attributes. A common example is to create one version of the role with the attribute country and the value USA and another version of the role with the value Germany for country. They are based on the same role template. Roles are then bundled into role collections for assignment to users.

If you want the developer view, check out the developer guide [here](https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/419ae2ef1ddd49dca9eb65af2d67c6ec.html). 

To get an overview of the role collections and roles SAP delivers with SAP BTP, check out [this document](https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/0039cf082d3d43eba9200fe15647922a.html). At the end of the document you can even see the role templates associated with the roles.

**Comment by MichaelPShea** [comment]
Let me know if the comment doesn't answer your question.

**Comment by i801193** [comment]
Thank you for the explanation.

**Comment by nikolasimeonov77** [comment]
This is not
