### ISSUE TITLE
Feedback for "Authentication and Authorization in the Kyma Environment"

### ISSUE THREAD

**Issue by jadolf** [SAP-docs/btp-cloud-platform#43]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/85200d8509004236b2a3a637bf1471a8.html?locale=en-US&version=Cloud

Small typo:    Ttherefore, ....

**Comment by mmitoraj** [comment]
I fixed the spelling in the 2202a version.

**Comment by NHingerl** [comment]
Thank you @mmitoraj ! 
The fix will be published March 10th.
