### ISSUE TITLE
Feedback for "Modules" - Invalid YAML 

### ISSUE THREAD

**Issue by piejanssens** [SAP-docs/btp-cloud-platform#45]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/177d34d45e3d4fd99f4eeeffc5814cf1.html?locale=en-US&version=Cloud

**Comment by lilyanarangelova** [comment]
Hi @piejanssens ,
Thank you for your feedback.  Could you please clarify which YAML is invalid?

Best regards,
Lilyana

**Comment by lilyanarangelova** [comment]
Hi,
The example has been updated:
![Screenshot 2022-03-18 at 13 59 17](https://user-images.githubusercontent.com/30077871/158999470-593b4325-2ddc-46ae-963b-a9ee32a0c8f8.png)

**Comment by piejanssens** [comment]
> Thank you for your valuable feedback contribution, @piejanssens! So that we can [recognize your contribution in SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please tell us your SAP Community profile URL in a reply to this comment; don't include any other text, just the URL on its own, like this:
> 
> ```
> https://people.sap.com/your-user-name
> ```
> 
> Thanks!

https://people.sap.com/piejanssens
