### ISSUE TITLE
Feedback for "Regions and API Endpoints Available for the Cloud Foundry Environment"

### ISSUE THREAD

**Issue by jrbpraven** [SAP-docs/btp-cloud-platform#46]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/f344a57233d34199b2123b9620d0bb41.html?locale=en-US

Hi, I am worry for this content because sometimes the IP adressess in this document are updated, and people don't know when there are new ip adressess. So I think, could you put this information in a SAP Note? As you know, People can set a SAP Note as a favorite, and an email is sent each time the SAP note is updated. I think it would be very usefull.

But, if there is another way to get that kind of notification, please write me.

I'm lokking forward for yout response.

Kind Regards

**Comment by sdanter** [comment]
Hi @jrbpraven, 

thank you for reaching out. I understand your concerns and we will take your feedback into consideration. 

In the meantime, let me tell you about the current channels and procedures surrounding changes to Regions information. There are two channels through which changes to the Regions information are announced: **What's New Release Notes** & the **Cloud System Notification Subscriptions (CSNS)** application which can be accessed through the **Cloud Availability Center** (CAC).

You can subscribe to the release notes to make sure you get the notifications there, but you can also check the release notes manually for information related to Regions by heading to the [What's New Viewer](https://help.sap.com/doc/43b304f99a8145809c78f292bfc0bc58/Cloud/en-US/98bf747111574187a7c76f8ced51cfeb.html) and filtering for the Region component.

If you want to also receive notifications through CAC/CSNS, you can subscribe to the foundational services for SAP BTP profile. You can find it using the Cloud Service filter in the CSNS application. For more information on CSNS, please refer to the User Guide [here](https://support.sap.com/content/dam/support/en_us/library/ssp/my-support/systems-installations/cac/csns_user_guide.pdf).

For general information on Platform Updates and Notifications, also see https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/99070c7bfc0e4f41842bd7c648b7fca7.html. It also contains some information about the reasons for Regions updates. 

I hope this helps.

**Comment by nikolasimeonov77** [comment]
Hi @jrbpraven
The document https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/99070c7bfc0e4f41842bd7c648b7fca7.html?version=Cloud is published with the new content.

**Comment by jrbpraven** [comment]
Dear Nikola Simeonov,

Many thanks for your help, I think is much more clear in that way, it looks great!.

Have a nice day/night.
