### ISSUE TITLE
Feedback for "Org Management Using the SAP BTP Command Line Interface (btp CLI) [Feature Set B]"

### ISSUE THREAD

**Issue by andrewgbeck** [SAP-docs/btp-cloud-platform#48]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/aee40e1afa56445a9bd57c2621d6eaaa.html

Hello, I found the API and the documentation to be confusing because it's not consistent with with the BTP Cockpit and its terminology. I expect that most users are like me, and start by learning the processes and terminology from BTP Cockpit to manually create and update configuration. When I started to implemented scripted processes, my first instinct was naturally to assume that the processes and vocabulary were the same as in the Cockpit. Where they are consistent - which is most of the time - it's quite intuitive. However, for the Cockpit process "Enable Cloud Foundry", the equivalent API (btp create accounts/environment-instance) is quite different in some key aspects - eg API: "display-name" "parameters{instance-name:<value>}" BTP contradictory names: see screen shot attached 

![Screenshot Enable Cloud Foundry](https://user-images.githubusercontent.com/11916943/157311101-b2377c60-4e97-41d7-ab54-9412f0299d40.png)

IMHO it would be better to explicitly document the differences between API and Cockpit. I am sure this is extra work if the Cockpit and API are developed by different teams, but that's SAP's problem, not the user's.

**Comment by andrewgbeck** [comment]
BTW I'm happy to have a call and show you what I'm doing in more detail, or review Help changes, if that's helpful.

**Comment by danielforsap** [comment]
Hello @andrewgbeck.
Are you an SAP employee?
We could have a Teams meeting at some time and discuss this in more detail.

Thanks,
Daniel

**Comment by danielforsap** [comment]
Hi @andrewgbeck,

I will send you an email with the detailed explanation what I have changed. 
If you have any further questions, please use the email to respond. 

Thank you for your contribution,
Daniel
