### ISSUE TITLE
Feedback for "Add Custom SOAP Header Elements"

### ISSUE THREAD

**Issue by gpaliot-eurosec** [SAP-docs/btp-cloud-platform#49]
Hi,

regarding https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/3dadfa903a11457d92248bccaa44fa27.html?locale=en-US&version=Cloud

I think there's a typo in the example:

`ws_header_facade->add_soap_header_element( xml_element).`

should be

`ws_header_facade->add_soap_header_element( xml_element ).`

otherwise I get a syntax check error in ADT, saying

_The statement concluding with "...XML_ELEMENT)" ended unexpectedly._

Best regards

Guido

**Comment by felixdraeger** [comment]
Hello Guido,
thank you for your feedback. I will check this issue with the responsible development colleagues.

Kind regards
Felix
