### ISSUE TITLE
Link in "Blue-Green Deployment Strategy" SAP Help is dead

### ISSUE THREAD

**Issue by turkishmaid** [SAP-docs/btp-cloud-platform#5]
re. https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/7c83810c31d842938cbc39c135a2d99f.html?locale=en-US

The link given under

> ### Results
> You can see an example of the process at [Blue-Green Deployment](https://help.sap.com/products/link-disclaimer?site=https%3A%2F%2Fgithub.com%2FSAP-samples%2Fcf-mta-examples%2Ftree%2Fmaster%2Fblue-green-deploy)

points to https://github.com/SAP-samples/cf-mta-examples/tree/main/blue-green-deploy which 404s for me.

**Comment by nikolasimeonov77** [comment]
Hello,
Could you please check if the link https://github.com/SAP-samples/cf-mta-examples/tree/main/blue-green-deploy is working now? I just tried it on another device outside the corporate network, and I can open it.

Thanks!

**Comment by dianamadzharova** [comment]
Hello,

The link no longer works. This is the new one - cf-mta-examples/blue-green-deploy-strategy at main * SAP-samples/cf-mta-examples * GitHub<https://github.com/SAP-samples/cf-mta-examples/tree/main/blue-green-deploy-strategy> it was also changed in the documentation. You can see the changed link here.<https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/7c83810c31d842938cbc39c135a2d99f.html>

Best regards,
Diana

**Comment by lilyanarangelova** [comment]
The link has been fixed
