### ISSUE TITLE
Feedback for "Access a Kyma Instance Using kubectl"

### ISSUE THREAD

**Issue by sebbae** [SAP-docs/btp-cloud-platform#50]
Hello,

at the moment of raising this issue, the documentation section for accessing the Kyma cluster via `kubectl` (https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/3e25944e491049b2aeec68c562a5ee48.html) is out of sync with the live functionality provided in the SAP BTP Cockpit for at least the productive landscapes *EU10* and *trial*.

The referred to link **KubeconfigURL** is not present and, thus, the described functionality is not accessible. For the moment, it is not obvious if the documentation is wrong or at least unclear or if the BTP Cockpit does not provide the functionality as described.

Best Regards,
Sebastian

![btp_cockpit_kyma_kubeconfig_missing_report](https://user-images.githubusercontent.com/2325250/158708466-4104e5b6-6cd6-412a-8f0e-c40775498989.png)

**Comment by NHingerl** [comment]
Hi Sebastian, thank you for raising this ticket! I see you're in contact with our experts in the support channel as well. 
Once the problem is solved there, we can adjust the docs as needed.

**Comment by klaudiagrz** [comment]
I think point no.2 in the instruction is redundant:
```2. In the SAP BTP cockpit, in your subaccount Overview, in the Kyma Environment section, select Manage environment instance.```

The link to KubeconfigURL is visible right in the Subaccount Overview:

<img width="844" alt="Screen Shot 2022-03-22 at 15 46 32" src="https://user-images.githubusercontent.com/35192450/159509449-880de44d-ac5b-405c-9e56-91e517551a72.png">

**Comment by grego952** [comment]
The updated instructions should help avoid this problem in the future.
![image](https://user-images.githubusercontent.com/62639546/159699683-074bc82a-8f8c-4035-89ab-19eeb8e30bc0.png)
