### ISSUE TITLE
Feedback for "Technical Communication with Tightly Coupled Developments"

### ISSUE THREAD

**Issue by corporateuser** [SAP-docs/btp-cloud-platform#51]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/92d82380f45a45c4b157f92a61307da1.html?locale=en-US

`cf create-service xsuaa application servb-uaa -c /appa/security/xs-security.json` why do we use App A xs-security.json for servb-uaa? 
Also several lines down:
`cf create-service xsuaa application appa-uaa -c /servb/security/xs-security.json` we're using Serv B xs-security.json for appa-uaa.
Looks inconsistent or it needs more clarifications.

**Comment by MichaelPShea** [comment]
Nope, I just mixed it up. Thanks for pointing it out. I will switch them republish. The update should show up on the Help Portal in about a month.

**Comment by MichaelPShea** [comment]
I will close this issue.
