### ISSUE TITLE
Feedback for "Using Kyma Eventing with SAP Event Mesh"

### ISSUE THREAD

**Issue by artemkovalyov** [SAP-docs/btp-cloud-platform#56]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/407d1266017f4b529b61665fa7408c41.html?locale=en-US&version=Cloud

The link is broken: "[Trigger a Function with an Event](https://help.sap.com/docs/link-disclaimer?site=https%3A%2F%2Fkyma-project.io%2Fdocs%2Fkyma%2Flatest%2F03-tutorials%2F00-application-connectivity%2Fac-07-trigger-function-with-event%2F)Information published on non-SAP site

**Comment by NHingerl** [comment]
Hi @artemkovalyov, thanks for noticing this! We'll fix it with the next possible publication.
