### ISSUE TITLE
Feedback for "Assign Roles in the Kyma Environment"

### ISSUE THREAD

**Issue by jalibu** [SAP-docs/btp-cloud-platform#57]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/148ae38b7d6f4e61bbb696bbfb3996b2.html?locale=en-US

```
Assign Roles in Kyma 2.x
Results
The users have the required authorizations as developer, and can access Kyma Console/Dashboard.
```

This statement is wrong, confusing, misleading or at least incomplete. Developers with namespace-only permissions can NOT access the Kyma Dashboard in general.

**Comment by NHingerl** [comment]
Dear @jalibu, thank you for your feedback!

We're going to publish an update to this topic, where the result has been changed to the following:

<img width="704" alt="image" src="https://user-images.githubusercontent.com/76950046/161970526-804f0cb2-cb98-4473-be68-57ce9d432062.png">


Will this solve the issue, or would you suggest other improvements?

**Comment by jalibu** [comment]
"The users have the required authorizations as developer within the specified namespace. If they do not have a ClusterRoleBinding to list namespace resources, they can still access the Kyma Dashboard but are asked to enter their Namespace name manually"

**Comment by jalibu** [comment]
@NHingerl see my post above. I'd phrase it like that.

**Comment by NHingerl** [comment]
@jalibu thanks a lot!

Handing this over to @grego952 who's our expert for Kyma Dashboard :)

**Comment by grego952** [comment]
@jalibu Once again, thank you for your comment.

After consulting the Dashboard team PO and @NHingerl we came up with the following solution:
`By default, the users have the authorizations as kyma-developer within the specified Namespace, and can enter Kyma Dashboard. Users without the permissions to view the list of Namespaces must enter the Namespace name they want to see.
If users need access to resources other than the default, they must clone the kyma-developer role and add the missing resources.`

Let me know what you think. Thanks!

**Comment by jalibu** [comment]
`By default, the users have the authorizations as kyma-developer within the specified Namespace` that's not true.

**Comment by grego952** [comment]
Thanks @jalibu for your comment. You're right, the `by default` wording may be misleading. We will drop this, so it says:
`The users have the authorizations as kyma-developer within the specified Namespace, and can enter Kyma Dashboard. The users without the permissions to view the list of Namespaces must enter the Namespace name they want to see. If the users need access to resources other than the default, they must clone the kyma-developer role and add the missing resources.`
Let me know if this is ok. Thank you :)

**Comment by jalibu** [comment]
`
[...] and can enter Kyma Dashboard.[...]
`
That's not a result of the role binding. Every user can enter the Kyma Dashboard, so this sentence is misleading.


```
The users have kyma-developer permissions within the specified Namespace. If the users do not have additional cluster role bindings to list the namespaces, they can still use the Kyma Dashboard overview but must enter the Namespace name they want to see manually.
If the permissions of the kyma-developer role are not sufficient, the role can be cloned and missing resources can be added.
```

**Comment by grego952** [comment]
Thank you @jalibu for your comment. Your suggestion has been applied. It should be visible with the next takt release (5th of May). Please take a look once more and provide your feedback.
![image](https://user-images.githubusercontent.com/62639546/165285552-0eb2e3f5-645e-489e-b993-676589c388ea.png)
