### ISSUE TITLE
SaaS registry issue : Not able to subscribe to multi-tenant application in the subscriber sub account

### ISSUE THREAD

**Issue by murthyvsap** [SAP-docs/btp-cloud-platform#63]
**Description of erroneous behaviour**
we are building a multi-tenant application using the guideline : https://cap.cloud.sap/docs/guides/deployment/as-saas

We have been advised by cap colleagues to raise SaaS registry issue.

the deployment went through , but subscription of the application fails with following error :
![image](https://user-images.githubusercontent.com/44488642/166269061-87076ae9-664e-4900-877e-079c7eeed8fa.png)

**Detailed steps to reproduce**:
For example (→ replace by appropriate ones for your case):

1) git clone https://github.com/danielsdevhub/AuthorReadings.git
in the above git repo : https://github.com/danielsdevhub/AuthorReadings/tree/main/application/author-readings-mt-noui
2) try deployment and registering to the service "author-readings" in subscriber sub-account.
we get the following issue : **Couldn't create the subscription to application** 'author-readings'. Please view details for more information. **Internal Server Error (500)**

![image](https://user-images.githubusercontent.com/44488642/166269189-933fbaf7-dfe6-4e65-8394-b80bda8ab020.png)
![image](https://user-images.githubusercontent.com/44488642/166269216-51ccf042-f31f-4489-906c-9ba9a0851653.png)

**Comment by renejeglinsky** [comment]
Hi @murthyvsap ,

this is a public repository meant for contributions to our BTP documentation. It's not a support channel. Therefore I'm closing this issue.

Check out the documentation on [Gettng Support](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/5dd739823b824b539eee47b7860a00be.html)

All the best,
René
