### ISSUE TITLE
Feedback for "Regions and API Endpoints Available for the Cloud Foundry Environment"

### ISSUE THREAD

**Issue by boyan-velinov** [SAP-docs/btp-cloud-platform#64]
Hello,

There is not API endpoint for EU10-004 in the page:
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/f344a57233d34199b2123b9620d0bb41.html

Only IPs are mentioned. The proper API endpoint is:
https://api.cf.eu10-004.hana.ondemand.com

Best Regards,
Boyan

**Comment by sdanter** [comment]
Thank you for your feedback, I will discuss this with the team and get back to you.

**Comment by sdanter** [comment]
Hello @boyan-velinov,

I have updated the documentation accordingly. The regions table will contain the API endpoint for eu10-004 after the next release. 

Thanks again and have a great week!

Stefan
