### ISSUE TITLE
Feedback for "Supported Protocols and Authentication Methods"

### ISSUE THREAD

**Issue by thomaswiegandsap** [SAP-docs/btp-cloud-platform#66]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/437e9d41d24349c3a2b363f726022677.html?version=Cloud

Typo:
> The supported protocols and authentication methods only apply to communication scenarios that are manage**y** by customers.

_(only via service destination)_ Not required, as the column is anyways already indicating Destination Service usage
> Principal Propagation (only via service destination)

**Comment by felixdraeger** [comment]
Thanks for the comments. I adjusted the documentation.

**Comment by thomaswiegandsap** [comment]
https://people.sap.com/thwiegan
