### ISSUE TITLE
Feedback for "SAP Business Technology Platform"

### ISSUE THREAD

**Issue by venkateshkasiraj** [SAP-docs/btp-cloud-platform#69]
SAP discovery services hyperlink is broken
https://discovery-center.cloud.sap/viewServices

[SAP Discovery Center: Service Catalog.](https://help.sap.com/docs/link-disclaimer?site=https%3A%2F%2Fdiscovery-center.cloud.sap%2FviewServices) in below page has issue
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/6a2c1ab5a31b4ed9a2ce17a5329e1dd8.html

**Comment by iwonahahn** [comment]
Hi @venkateshkasiraj,

Thank you for your feedback. There was a downtime last week but the service catalog is back again. Sorry for any inconvenience caused by this. 

Best regards,
Iwona
