### ISSUE TITLE
Feedback for "Customizing the Java Virtual Machine (JVM) Settings"

### ISSUE THREAD

**Issue by rbrede** [SAP-docs/btp-cloud-platform#7]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/b8cda61d3d984e259f1de8816e52ec47.html?locale=en-US&version=Cloud

The examples did not work for me. I had to omit the brackets [ ]. (I also skipped the from_environment: false) then it worked ...

Best regards,
Reinhard

**Comment by Joysie** [comment]
Hi Reinhard,

You are right! The brackets should be dropped, as well as this property (it's not really necessary). 

Documentation is fixed.  You will be able to see the changes on SAP Help Portal after the next content update.

Best regards,
Gergana
