### ISSUE TITLE
Feedback for "Account Model" - Spelling Mistake

### ISSUE THREAD

**Issue by Milton-Rodrigues** [SAP-docs/btp-cloud-platform#70]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/8ed4a705efa0431b910056c0acdbf377.html?locale=en-US&state=PRODUCTION&version=Cloud

Please check for spelling mistakes. There is a line here
"A global account is the realization of a contract you or your comaony made with SAP."
The word 'company' is mis-spelled

**Comment by nikolasimeonov77** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by annawenger20** [comment]
Hi @Milton-Rodrigues - thanks for spotting this! It's been fixed and will be visible with the next release on SAP Help Portal. 
Thanks, Anna

**Comment by Milton-Rodrigues** [comment]
https://people.sap.com/milton.reubenrodrigues
