### ISSUE TITLE
Feedback for "Audit Logging in the Cloud Foundry Environment"

### ISSUE THREAD

**Issue by jung-thomas** [SAP-docs/btp-cloud-platform#71]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/f92c86ab11f6474ea5579d839051c334.html
The video embedded in this page https://youtu.be/XUJ0mmO-dLA - reports that it is unavailable as it is marked as private.

**Comment by nikolasimeonov77** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by petiansap** [comment]
@jung-thomas, thank you for youe feedback. I removed the video as it is no longer available.

**Comment by iwonahahn** [comment]
Hi @jung-thomas,

The page was updated and therefore we close this issue.

Best regards,
Iwona
