### ISSUE TITLE
Feedback for "Getting Started in the Kyma Environment"

### ISSUE THREAD

**Issue by KevinMuessig** [SAP-docs/btp-cloud-platform#75]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/d1abd18556f24fb091d081b2e3454b8b.html?

Would be helpful to also mention Free Tier. At the moment the documentation only has links saying:
- "Getting Started with an Enterprise Account in the Kyma Environment"
- "Getting Started with a Trial Account in the Kyma Environment"

Maybe have Free Tier in there as well.

**Comment by nikolasimeonov77** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by majakurcius** [comment]
Hi, @KevinMuessig! 
This is already being worked on. 
We have our own internal ticket for this (not going to link it here for security reasons), so I'm going to close yours.
Thank you for your contribution 😊

**Comment by KevinMuessig** [comment]
https://people.sap.com/kevin.muessig
