### ISSUE TITLE
Feedback for "Extending SAP Solutions Using Automated Configurations"

### ISSUE THREAD

**Issue by MichaelCzcz** [SAP-docs/btp-cloud-platform#76]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/346864df64f24011b49abee07bbd79af.html

This page was not found.

**Comment by nikolasimeonov77** [comment]
Hi @MichaelCzcz,
Which page is not found? I can open https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/346864df64f24011b49abee07bbd79af.html?

**Comment by MichaelCzcz** [comment]
The page named "Extending SAP Solutions Using Automated Configurations" just showed the text "This page was not found.". Seems to have been a temporary problem.

**Comment by MichaelCzcz** [comment]
https://people.sap.com/michaelcz
