### ISSUE TITLE
Feedback for "OData Services"

### ISSUE THREAD

**Issue by xavergr** [SAP-docs/btp-cloud-platform#77]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/811b5231f77e4987abe8e985e32f70a1.html?locale=en-US

Hi SAP,
in the following Link the Documentation for Interaction between SAP BTP, ABAP Environment and OData is incomplete. The Site of the Link itself is incomplete, aswell as most of the Chapters under this Section are missing/incomplete.

best Regards,
Xaver

**Comment by nikolasimeonov77** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by DK1808** [comment]
Hi @xavergr, the documentation is currently being reworked and will be updated as soon as possible. Thanks again for your contribution!
