### ISSUE TITLE
Feedback for "Cloud Foundry Environment"

### ISSUE THREAD

**Issue by daniil-bolobonov** [SAP-docs/btp-cloud-platform#81]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/9c7092c7b7ae4d49bc8ae35fdd0e0b18.html

In the documentation "Sharing Service Instances" is mentioned in 'Supported Features' column. 
However, **"service instance sharing" is not supported** by SAP BTP as per KB https://launchpad.support.sap.com/#/notes/0003069860 and our tests.

We also found some questions on Community Page that talk about that issue: 
https://answers.sap.com/questions/13611699/sharing-service-instances-supportednot-supported-c.html
https://answers.sap.com/questions/702091/service-instance-sharing-on-sap-cp-cf.html

**Comment by DavidMitreski5** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by sdanter** [comment]
Hello @daniil-bolobonov, thank you for reaching out. SAP BTP as a platform in principle does support instance sharing, but not all SAP BTP services support this feature. Hence the disclaimer in the topic you linked. We will update the documentation gradually to provide further information on this.
