### ISSUE TITLE
Feedback for "Create Space Quota Plans Using the Cloud Foundry Command Line Interface"

### ISSUE THREAD

**Issue by danachkov** [SAP-docs/btp-cloud-platform#83]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/504fde98e8bb4bff889e49d0b2f6c28b.html

There is a typo in the code sample. The parameter should be --allow-paid-service-plans instead of --allow-paid-service-plan.

**Comment by slavipande** [comment]
Thank you very much for pointing that out. I have fixed the typo.
