### ISSUE TITLE
Feedback for "Getting an Access Token for SAP Cloud Management Service APIs"

### ISSUE THREAD

**Issue by stephanzlatarev** [SAP-docs/btp-cloud-platform#86]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/3670474a58c24ac2b082e76cbbd9dc19.html

As understood in step 1 one has to create the service instance in "Runtime Environment: Other Environments" otherwise it simply doesn't work. Currently this documentation page lists "Cloud Foundry" as the first option for the user to choose from. Cloud Foundry is a dead end for this particular case. The user should not even be shown it as an option. Rather, the documentation should clearly state to NOT choose Cloud Foundry in step 1.

In addition, the documentation page gives notes about "getting an application access token for the APIs of SAP Software-as-a-Service Provisioning service" which seem irrelevant. It does not describe why the user may be interested in "Provisioning service" when reading about "Account Administration". You may consider either introducing "Provisioning service" and its relevance to the topic in the notes, or alternatively removing those notes altogether.

**Comment by MGruenhagel** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by danielforsap** [comment]
Hi @stephanzlatarev,

After consulting with the PO, we've decided to remove the notes that mention SAP Software-as-a-Service Provisioning service.
Regarding your other point, we should further discuss it.

Kind regards,
Daniel
