### ISSUE TITLE
Feedback for "Dynatrace Integration"

### ISSUE THREAD

**Issue by stephan-bosch** [SAP-docs/btp-cloud-platform#88]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/1610eac123c04d07babaf89c47d82c91.html?q=dynatrace%20cloud%20foundry

The API url format has changed. 

The new url format is now https://<-environment-id->.live.dynatrace.com/api

**Comment by stephan-bosch** [comment]
HI Gergana,

Thank you for taking the time.

The fact that there is PasS and Managed format and only the managed is covered does not seem right to me.
If there is a DynaTrace SaaS help page then I think it is worth referencing.

It does not hurt to include a mention if using SaaS this format should be used instead of managed.

Hope this provides some constructive feedback.

Kind regards,

Stephan

**Comment by Joysie** [comment]
Hi Stephan,

Thank you again for the great feedback! 
I consulted with my Java team colleagues and they confirmed that actually **both types** are supported - depending on what Dynatrace integration the customer is using. 
So this clarification has been reflected in the documentation.  The changes will be visible on the Help Portal with the next release.

Best regards,
Gergana

**Comment by Joysie** [comment]
Hi Stephan,

Docu page is updated. See:  https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/1610eac123c04d07babaf89c47d82c91.html?version=Cloud

Thank you again for your feedback and contribution!

**Comment by DavidMitreski5** [comment]
Hello @stephan-bosch & @Joysie, it seems like this issue has been resolved and it stayed open for too long; Therefore I'm closing it.
Thank you for your feedback and contribution!
