### ISSUE TITLE
Feedback for "Developing Java in the Cloud Foundry Environment"

### ISSUE THREAD

**Issue by xudonny** [SAP-docs/btp-cloud-platform#9]
Hi colleagues,
This guide
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/a3f90069d6cd41da82f34a6123d82ce6.html --> components mentioned calculator V1 is by default
Memory Calculator V1 (SAP JVM Memory Calculator) - by default

But in guide Memory Calculator
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/505a71ae53e84c7a972bb6c34b4316fb.html
V2 is marked as default:
Memory Calculator V2 - this memory calculator is activated by default.

May I know which version exactly is used by default in sap java buildpack? 

Thanks,
Donny

**Comment by Joysie** [comment]
Hi Donny,

The Memory Calculator **V2** is the default version. Documentation page [Developing Java in the Cloud Foundry Environment](https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/a3f90069d6cd41da82f34a6123d82ce6.html) has been corrected. 

Thank you for the valuable feedback!

Best regards,
Gergana
