### ISSUE TITLE
Issue with BTP Release Notes

### ISSUE THREAD

**Issue by thoHeinze** [SAP-docs/btp-cloud-platform#92]
Hi colleagues, 

I'm trying to find a specific old release note for the service "MongoDB" and "RabbitMQ" from 2019. The release note in the past was accessible via https://help.sap.com/doc/eed1e41fe772463c8ce3fdfa1ca6e57f/Cloud/en-US/98bf747111574187a7c76f8ced51cfeb.html?from=2019-01-01&to=2019-12-31 
and looked like this in the screenshot:
![image](https://user-images.githubusercontent.com/8880300/183074971-29b7175f-cd69-4d68-a653-43e52e0aa047.png)

I can't find this release note in the new search field https://help.sap.com/doc/eed1e41fe772463c8ce3fdfa1ca6e57f/Cloud/en-US/98bf747111574187a7c76f8ced51cfeb.html?from=2019-01-01&to=2019-12-31&sel1=RabbitMQ
It says "3 entries" but shows nothing.

**Comment by renejeglinsky** [comment]
Hi @thoHeinze ,

please try the table view:
![image](https://user-images.githubusercontent.com/32062331/183080903-501a593a-1767-4111-b094-ee96c48ff140.png)

For whatever reason using that one it shows the entries for me.

All the best,
René

**Comment by renejeglinsky** [comment]
Of course we'll look into this bug, but I think there's no need to keep this issue open for that. 
Thanks for creating your first issue 👍

**Comment by thoHeinze** [comment]
@renejeglinsky  Nearly one year later, the issue is closed, but the problem is still there. Any update?

**Comment by renejeglinsky** [comment]
Hi @thoHeinze ,
please use this link as a workaround: https://help.sap.com/docs/RabbitMQ/15a22358e1984002b6b8ecd55960f49f/d7eca291c0924fafabf3e41a7ad34fd7.html

All the best,
René
