### ISSUE TITLE
Feedback for "Deploy Content Using HTML5 Application Deployer"

### ISSUE THREAD

**Issue by Pavithra0705** [SAP-docs/btp-cloud-platform#95]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/9b178ab3388c4647b0c52f2c85641844.html

The last configuration file called mtad.yaml  is no where in the project structure . Is manifest.yaml and mtad.yaml content the same ?

**Comment by SarahErdmann** [comment]
Hi @Pavithra0705, Thank you for your valuable feedback! 
We are currently correcting this Help Portal page. In step 3, it should say "Create an mta.yaml file (MTA development descriptor file)." (not mtad.yaml file). SAP cf deploy service (—> cf deploy  .)The build of the mta.yaml file leads to the creation of an *.mtar file (MTA archive) which contains the mtad.yaml file (MTA deployment descriptor).  For more information about the MTA descriptor files, see https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/d04fc0e2ad894545aebfd7126384307c.html .

manifest.yaml is the deployment descriptor /app manifest used for Cloud Foundry's cf push command. It is not relevant here.
