### ISSUE TITLE
Feedback for "Register an SAP SuccessFactors System in a Global Account in SAP BTP"

### ISSUE THREAD

**Issue by piejanssens** [SAP-docs/btp-cloud-platform#96]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/e956ba209f30447cb55140e38c15e345.html?locale=en-US

Please provide new instructions, now that Extension Center is about to be removed from SuccessFactors.

![Screen Shot 2022-08-19 at 12 47 56 PM](https://user-images.githubusercontent.com/829098/185602826-045a2166-ad7e-489e-a70e-78fa04a66ed3.png)

**Comment by ekaterina-mitova** [comment]
Hi @piejanssens,
The Extension Center with the extensions on SAP BTP will remain the same. The SuccessFactors extensions functionality will be removed from this tool. So, the warning is applicable only to the SuccessFactors extensions. 

Best regards, 
Ekaterina

**Comment by piejanssens** [comment]
https://blogs.sap.com/2021/10/14/introducing-the-reworked-steps-for-extending-sap-successfactors-on-sap-business-technology-platform/comment-page-1/#comment-635556
