### ISSUE TITLE
Feedback for "Extending SAP SuccessFactors in the Cloud Foundry and Kyma Environment"

### ISSUE THREAD

**Issue by piejanssens** [SAP-docs/btp-cloud-platform#97]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/9e33934540c44681817567d6072effb2.html?locale=en-US

Please provide documentation for "SAP SuccessFactors Extensibility" service's `sso-configuration`plan.

**Comment by ekaterina-mitova** [comment]
Hi @piejanssens, 

The documentation is already prepared for the release next week. 

Best regards, 
Ekaterina
